### ISSUE TITLE
feature request mmu home before every toolchange

### ISSUE THREAD

**Issue by rwijnhov** [moggieuk/Happy-Hare#106]
Sometimes my selector moves a tiny bit. then after 50+ changes it will be to much so it block the gate to enter filament. If there would be an option to home the selector befor every change this would never be a problem.

**Comment by moggieuk** [comment]
If the selector moves then I think there is a mechanical problem.   That would be equivalent to a layer shift on a print.  Maybe up the "hold" current of the selector stepper a little?

If you really want to home on every tool change then there is enough customization to do this.  One way would be to turn on the gocde load sequence and add a mmu_home at the beginning of that logic.  You can read about that here: 
https://github.com/moggieuk/Happy-Hare/blob/main/doc/gcode_customization.md#---_mmu_load_sequence--_mmu_unload_sequence
