### ISSUE TITLE
Internal error during connect: 'Mmu' object has no attribute 'EXTRUDER_ENSTOPS'

### ISSUE THREAD

**Issue by afllak** [moggieuk/Happy-Hare#107]
After doing the latest updates klipper start throwing this error (Internal error during connect: 'Mmu' object has no attribute 'EXTRUDER_ENSTOPS').
Any advice on how to fix this error.

Thank you.

**Comment by moggieuk** [comment]
That was fixed.  Can you make sure you are up-to-date.  Force an update-manager refresh if necessary..

**Comment by afllak** [comment]
Yes, fixed thank you.
