### ISSUE TITLE
Impossible to define a gate endstop due to names being misaligned

### ISSUE THREAD

**Issue by dflemstr** [moggieuk/Happy-Hare#114]
The filament sensor for the MMU gate is sometimes in the code called `"mmu_gate"` and sometimes just `"gate"`. Parts of the documentation before the addition of `[mmu_sensors]` made it sound like the endstop could be fully customized, but now it seems like it absolutely needs to be called exactly `"mmu_gate"`.

I think that either enforcing the convention of calling it `"mmu_gate"` or else consistently allowing the name to be customized would fix this bug.  I'll create a PR corresponding to the first approach.

**Comment by moggieuk** [comment]
I added some comments in the PR, but to add more color...
My convention was to use 'mmu_XX'.  BUT the toolhead sensor name (acting as a sensor) was historically called 'toolhead' and I was reluctant to change.    Maybe I'm being paranoid but I guess the two filament sensors 'extruder' and 'toolhead' could both be 'mmu_XXX' too...

Yes, the strings should be constants.

Yes and endstop can be used (but not with Happy Hare default logic).  You can use commands like 'MMU_TEST_HOMING_MOVE ENDSTOP=anything_you_like MOVE=` but for configuration the consistency makes it manageable.
