### ISSUE TITLE
An Upgrade routine is required

### ISSUE THREAD

**Issue by lettore** [moggieuk/Happy-Hare#122]
Upgrading happy hare is really a pain, with every new upgrades something is not working, now it complains about some LEDs. I don't even understand why if some functionality is added it should change the config reference that worked until the previous version.
I kindly ask you to introduce a upgrade.sh that translates a working config from a specific version to the new one. For example asking "you need LED support?" no as I don't have LEDs.
The install.sh method is not working, from a working setup it still complains about missing pin for tmc etc. Not really into parsing every file to understand what the script broken again

**Comment by salocain** [comment]
yes i agree with that , too many changes , and alway redo a config is a pain...

**Comment by moggieuk** [comment]
Well, I try very hard to make the install.sh perform and upgrade to existing configuration.  The installer is a HUGE time sink because of the difficulties in testing and the almost infinite starting points.  Would love some help on this....

**Comment by moggieuk** [comment]
Closing because this is old and HH doesn't use manual steppers anymore
