### ISSUE TITLE
Endless spool does not work when using filametrix

### ISSUE THREAD

**Issue by DarkSoulRL** [moggieuk/Happy-Hare#124]
Endless spool does not work when using filametrix. 

The cut filament is not long enough for the ERCF gears to grab it and pull it out. As a result, it does not pull out the filament and blocks the selector.
Printing stops with the error:
![image](https://github.com/moggieuk/Happy-Hare/assets/21101416/afdccdb4-7092-4c52-8bba-bc12aa8d96fe)

**Comment by DarkSoulRL** [comment]
Is it possible to make sure that the filament is not removed, but simply the selector goes to the next gate and pushes a new filament?

**Comment by DarkSoulRL** [comment]
I found the problem
![image](https://github.com/moggieuk/Happy-Hare/assets/21101416/af01687e-d71a-4b0e-b395-8124975bc2c2)


It seems to me that it would be worth limiting the autodetection of mmu_calibration_clog_length to some more real value, so that this would not happen. 7mm works great for me.

**Comment by moggieuk** [comment]
This may be hitting the limitation of the ERCF design.  There are some things you can do to make it work:
1. Shorten the clog detection length.  8-10mm should be possible.  This will result in earlier detection
2. [not ERCF, but MMU's with mmu_gate sensor would be able to detect much quicker than encoder]
3. Don't leave so much filament in the extruder.  You can turn filametrix to do an initial retraction.  Then you need only leave about 5mm of filament in the extruder.  Then you are liekly to have sufficent filament to push back.
4. With the new pre-gate sensor feature, runout can be triggered much earlier without issues with the gear picking up the filament or the filament catching when being fed backwards.

**Comment by moggieuk** [comment]
Reducing clog length worked, so closing this issue

**Comment by DarkSoulRL** [comment]
I no longer had this problem after upgrading to ERCF v2 + ERCT
