### ISSUE TITLE
Feature request: Calibrate selector conversational 

### ISSUE THREAD

**Issue by killboxalpha** [moggieuk/Happy-Hare#126]
I run a Tradrack and have my 0 gate ~100mm from the endstop switch, everytime I have to mod the mmu.py after a update with this info, during calibrate selector it states there is a problem, but this is the correct position. 

I'd really like it if I could override this during the calibrate, by stating yes no to is this correct, rather then going into the .py

Maybe also add a check where it tries to line up with the last gate to test final pos if the cad gates are slightly off, as well

**Comment by moggieuk** [comment]
With "none standard" setups you will need to set these params (also better to set vendor to "Other"):

Have are read here: https://github.com/moggieuk/Happy-Hare?tab=readme-ov-file#1-important-mmu-vendor--version-specification

(expand the section)

Note also I have a new v2.4 version coming out in days to make Tradrack support better.  If you have a non-standard setup you will still need to adjust these "cad" params though.
