### ISSUE TITLE
Feature Request: Filametrix Z pin location

### ISSUE THREAD

**Issue by Jameson42** [moggieuk/Happy-Hare#128]
I'm planning on putting Filametrix on my Enderwire, but I'd rather not lose X travel due to the Filametrix pin. I'm considering mounting the pin near the top of the Z axis... I figure CoreXZ can make super fast Z movements, why not make use of it? I'd love to see a configuration option within HH to allow for this mounting option. Basically, instead of moving in X and Y, a Switchwire Filametrix macro could move in X and Z.

**Comment by moggieuk** [comment]
That would be interesting to see a large z move.  It's not something that I can build because I don't have a setup to test on but also there is a servo activated pin option that you might want to consider.   It would be open to a PR request though.
