### ISSUE TITLE
_MMU_STEP_UNLOAD_ENCODER not work

### ISSUE THREAD

**Issue by Tutankamon00** [moggieuk/Happy-Hare#129]
i try to creatte my unload macro but after bowden unload i have to run _MMU_STEP_UNLOAD_ENCODER and it not work:
![immagine](https://github.com/moggieuk/Happy-Hare/assets/142754987/b9e0b824-9094-4f5e-8df4-4f5c8fd18801)

**Comment by moggieuk** [comment]
Ah, it is called `_MMU_STEP_UNLOAD_GATE`.   Does the same thing but works both with encoder or a gate_switch (like Tradrack design)

**Comment by Tutankamon00** [comment]
> Ah, it is called `_MMU_STEP_UNLOAD_GATE`. Does the same thing but works both with encoder or a gate_switch (like Tradrack design)
> 
> Do I have a bad reference to this in the doc?

![immagine](https://github.com/moggieuk/Happy-Hare/assets/142754987/524f6bd3-faad-48a3-bc4c-ec902d6958b4)

**Comment by moggieuk** [comment]
Doc has been fixed (finally!)
