### ISSUE TITLE
Section 'menu __main __mmu' is not a valid config section

### ISSUE THREAD

**Issue by marcus360** [moggieuk/Happy-Hare#131]
hi i get when trying to install happy hare with klipper screen this error : 

Section 'menu __main __mmu' is not a valid config section

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

i am giving you my klipper log and sorry but i didnt know where is this problem
[klippy (6).log](https://github.com/moggieuk/Happy-Hare/files/13799316/klippy.6.log)

**Comment by marcus360** [comment]
for future guys, if you dont have mini display dont install library to it :)

**Comment by Matze9876** [comment]
Hallo Marcus,

ich habe genau das gleiche Problem.
Wie konntest du es lösen?

Dank im Voraus
Gruß Matze
-----------------------------------------------------
Hello Marcus,

I have exactly the same problem.
How were you able to solve it?

Thanks in advance
Greetings Matze

**Comment by ningpj** [comment]
dont include ``optional/mmu_menu.cfg``.  These are menus for the original 12864 screen
