### ISSUE TITLE
MMU_ENCODER enable=0 seems reversed in document command reference.

### ISSUE THREAD

**Issue by julianjc84** [moggieuk/Happy-Hare#139]
**Help File:**
https://github.com/moggieuk/Happy-Hare/blob/main/doc/command_ref.md

"MMU_ENCODER | Displays the current value of the MMU encoder or explicitly enable or disable the encoder. Note that the encoder state is set automatically so this will only be sticky until next tool change | ENABLE=[0\|1] Enable/DisableVALUE=.. Set the current distance"

**ISSUE:**
it appears the Enable  and Disable  are reversed?
help file 
enable =0
disable = 1
in console on klipper
enable =1
disable -0

**CONSOLE output klipper:** 
happy-hare
v2.3.1-9-g3ffd36ef

07:15:50
Encoder position: 917.6
Clog/Runout detection: On (Detection length: 10.0)
Trigger headroom: 15.0 (Minimum observed: 10.0)
Flowrate: 0 %
07:15:50
MMU_ENCODER enable=1
07:15:44
Encoder position: 897.3
07:15:43
MMU_ENCODER
07:15:40
Encoder position: 886.5
07:15:39
MMU_ENCODER
07:15:34
MMU_ENCODER enable=0

**Comment by moggieuk** [comment]
I think you are referring to the doc saying:
```
ENABLE=[0|1] Enable/Disable
```
and wanting it to say:
```
ENABLE=[0|1] Disable/Enable
or
ENABLE=[0|1] 0=Disable, 1=Enable
```

Happy to change that but normally the convention is that 0=disable, 1=enable..
