### ISSUE TITLE
 Unnecessary waiting for the hotend to cool down.

### ISSUE THREAD

**Issue by DarkSoulRL** [moggieuk/Happy-Hare#141]
ABS was printed at a temperature of 280 degrees.
At the end of the work we see this.
![image](https://github.com/moggieuk/Happy-Hare/assets/21101416/38f2924f-813d-4726-b64a-e2455ce36711)

The current version of HH began to wait for the nozzle to cool down to 200g after printing in order to extract the filament. Why is this done, it is not required. The same thing happens when printing starts, if the nozzle was heated above 200 degrees, HH waits for it to cool down to 200 degrees.

**Comment by moggieuk** [comment]
So this is while printing?   Can you attach the `mmu.log`.   The logic around what temperature to be at is surprisingly complex...  the info you have giving me gives me a hint but the log would be better..

**Comment by DarkSoulRL** [comment]
look at 23:11:44, 
current_temp=270.76
Warning:  Automatically heating extruder to minimum temp (200.0)
[mmu.zip](https://github.com/moggieuk/Happy-Hare/files/13869473/mmu.zip)

**Comment by bartoszwas** [comment]
I had same error, it was PRINT_END macro issue when I turned off heaters first then try to unload. When i switched commands to first unload and then turn off heaters everytihng is fine. Just target temp was set to 0 so it had to reheat again.

**Comment by DarkSoulRL** [comment]
not the case
![image](https://github.com/moggieuk/Happy-Hare/assets/21101416/28263458-73f0-4bc7-8e3c-c2b65eb5ef1f)

**Comment by bartoszwas** [comment]
in your log there is:

18:49:10 - - TRACE: _ensure_safe_extruder_temperature: current_temp=268.71, paused_extruder_temp=None, **current_target_temp=0.0**, klipper_minimum_temp=170.0, default_extruder_temp=200.0, source=auto
18:49:10 Warning: Automatically heating extruder to minimum temp (200.0)

So something sets temp to 0.0 before unload. Don't you have doubled PRINT_END macro? Maybe Slicer turns off the heaters?
