### ISSUE TITLE
Suggestion: Spoolman integration 

### ISSUE THREAD

**Issue by spitfire1337** [moggieuk/Happy-Hare#15]
I know work is ongoing for V2 so just throwing this out there as a suggestion. Since we already have the capability to assign filament color and types to each tool, my idea is to be able to add spoolman IDs to each tool , and with spoolman integration native to moonraker we could then on tool change to update the assigned spool to the current tool and track usage for swaps.

**Comment by moggieuk** [comment]
It's a good idea and on the TODO list!  Will be after initial release though :-)

**Comment by meganssmith** [comment]
I Second the request

**Comment by lettore** [comment]
I'm already using this system from some time, personally I'm using the field material to store the numerical ID of the spool in Spoolman, then when I added a  command in ERCF action change macro to update the Spool with Moonraker
```
[gcode_macro _ERCF_ACTION_CHANGED]
description: Called when an action has changed.
gcode:
    # This occurs when the ERCF action status changes.  `printer.ercf.action` will contain
    # the current action string. See Happy Hare README for full list
    #
    # This could be a place to set LED status or similar. The logic here
    # demonstrates the three major action states
    {% set ACTION = printer.ercf.action|string %}

    {% if ACTION|string == "Idle" %}
        # Add your logic here
        # _STATUS_STANDBY
        {% if printer.ercf.tool|int > -1 %}
            #if material loaded is a number, then it should be a Spoolman ID
            {% if printer.ercf.material|int > 0 %} 
                #if material loaded is a number, then it should be a Spoolman ID
                {% if printer.ercf.filament == "Loaded" %} 
                {% set id = printer.ercf.material|int %}
                #set the spool ID
                {action_call_remote_method("spoolman_set_active_spool",spool_id=id)}
                {% else %}
                #clear spool ID as filament is not loaded
                {action_call_remote_method("spoolman_set_active_spool",spool_id=None)}
                {% endif %}
            #clear spool ID as it's invalid
            {% else %}
                {action_call_remote_method("spoolman_set_active_spool",spool_id=None)}
            {% endif %}     
        {% endif %}     
    {% endif %}
    
    {% if ACTION|string == "Loading" %}
        # Add your logic here
        # _STATUS_LOADING
    {% endif %}

    {% if ACTION|string == "Unloading" %}
        # Add your logic here
        # _STATUS_UNLOADING
        {action_call_remote_method("spoolman_set_active_spool",spool_id=None)}
    {% endif %}
```
Unfortunately this no longer works as it seems that on Happy Hare action changed is no longer called
```
[gcode_macro _MMU_ACTION_CHANGED]
description: Called when an action has changed
gcode:
    {% set ACTION = params.ACTION|string %}
    {% set OLD_ACTION = params.OLD_ACTION|string %}

    {% if ACTION|string == "Loading" %}
        # Add your logic here, e.g. loading LED
        # _STATUS_LOADING
    {% endif %}

    {% if ACTION|string == "Unloading" %}
        # Add your logic here, e.g. unloading LED
        # _STATUS_UNLOADING
        {action_call_remote_method("spoolman_set_active_spool",spool_id=None)}
    {% endif %}

    {% if ACTION|string == "Idle" %}
        # Add your logic here, e.g. LED off
        # _STATUS_STANDBY
        {% if printer.mmu.tool|int > -1 %}
            #if material loaded is a number, then it should be a Spoolman ID
            {% if printer.mmu.material|int > 0 %} 
                #if material loaded is a number, then it should be a Spoolman ID
                {% if printer.mmu.filament == "Loaded" %} 
                    {% set id = printer.mmu.material|int %}
                    #set the spool ID
                    {action_call_remote_method("spoolman_set_active_spool",spool_id=id)}
                {% else %}
                    #clear spool ID as filament is not loaded
                    {action_call_remote_method("spoolman_set_active_spool",spool_id=None)}
                {% endif %}
            #clear spool ID as it's invalid
            {% else %}
                {action_call_remote_method("spoolman_set_active_spool",spool_id=None)}
            {% endif %}     
        {% endif %}          
    {% endif %}
    
```
I spent 4 hours to make all working as in HH v1.1 and now I lost any will to fix also this issue.

**Comment by spitfire1337** [comment]
> I'm already using this system from some time, personally I'm using the field material to store the numerical ID of the spool in Spoolman, then when I added a command in ERCF action change macro to update the Spool with Moonraker
> 
> ```
> [gcode_macro _ERCF_ACTION_CHANGED]
> description: Called when an action has changed.
> gcode:
>     # This occurs when the ERCF action status changes.  `printer.ercf.action` will contain
>     # the current action string. See Happy Hare README for full list
>     #
>     # This could be a place to set LED status or similar. The logic here
>     # demonstrates the three major action states
>     {% set ACTION = printer.ercf.action|string %}
> 
>     {% if ACTION|string == "Idle" %}
>         # Add your logic here
>         # _STATUS_STANDBY
>         {% if printer.ercf.tool|int > -1 %}
>             #if material loaded is a number, then it should be a Spoolman ID
>             {% if printer.ercf.material|int > 0 %} 
>                 #if material loaded is a number, then it should be a Spoolman ID
>                 {% if printer.ercf.filament == "Loaded" %} 
>                 {% set id = printer.ercf.material|int %}
>                 #set the spool ID
>                 {action_call_remote_method("spoolman_set_active_spool",spool_id=id)}
>                 {% else %}
>                 #clear spool ID as filament is not loaded
>                 {action_call_remote_method("spoolman_set_active_spool",spool_id=None)}
>                 {% endif %}
>             #clear spool ID as it's invalid
>             {% else %}
>                 {action_call_remote_method("spoolman_set_active_spool",spool_id=None)}
>             {% endif %}     
>         {% endif %}     
>     {% endif %}
>     
>     {% if ACTION|string == "Loading" %}
>         # Add your logic here
>         # _STATUS_LOADING
>     {% endif %}
> 
>     {% if ACTION|string == "Unloading" %}
>         # Add your logic here
>         # _STATUS_UNLOADING
>         {action_call_remote_method("spoolman_set_active_spool",spool_id=None)}
>     {% endif %}
> ```
> 
> Unfortunately this no longer works as it seems that on Happy Hare action changed is no longer called
> 
> ```
> [gcode_macro _MMU_ACTION_CHANGED]
> description: Called when an action has changed
> gcode:
>     {% set ACTION = params.ACTION|string %}
>     {% set OLD_ACTION = params.OLD_ACTION|string %}
> 
>     {% if ACTION|string == "Loading" %}
>         # Add your logic here, e.g. loading LED
>         # _STATUS_LOADING
>     {% endif %}
> 
>     {% if ACTION|string == "Unloading" %}
>         # Add your logic here, e.g. unloading LED
>         # _STATUS_UNLOADING
>         {action_call_remote_method("spoolman_set_active_spool",spool_id=None)}
>     {% endif %}
> 
>     {% if ACTION|string == "Idle" %}
>         # Add your logic here, e.g. LED off
>         # _STATUS_STANDBY
>         {% if printer.mmu.tool|int > -1 %}
>             #if material loaded is a number, then it should be a Spoolman ID
>             {% if printer.mmu.material|int > 0 %} 
>                 #if material loaded is a number, then it should be a Spoolman ID
>                 {% if printer.mmu.filament == "Loaded" %} 
>                     {% set id = printer.mmu.material|int %}
>                     #set the spool ID
>                     {action_call_remote_method("spoolman_set_active_spool",spool_id=id)}
>                 {% else %}
>                     #clear spool ID as filament is not loaded
>                     {action_call_remote_method("spoolman_set_active_spool",spool_id=None)}
>                 {% endif %}
>             #clear spool ID as it's invalid
>             {% else %}
>                 {action_call_remote_method("spoolman_set_active_spool",spool_id=None)}
>             {% endif %}     
>         {% endif %}          
>     {% endif %}
>     
> ```
> 
> I spent 4 hours to make all working as in HH v1.1 and now I lost any will to fix also this issue.

That's an interesting method, looking at the new macros it looks like _MMU_POST_LOAD might be what you're looking for.

**Comment by lettore** [comment]
Yes maybe I will try, anyway I can't understand why _MMU_ACTION_CHANGED is provided but it's not working. Obviously this is not a solution as there's no check with Spoolman if the spool really exists or not. I will suggest for the future integration to enable double side communication with Spoolman and add a feature to check the filament amount remaining on the spool with Spoolman, then if endless spool is enabled change the filament before it trigger the anticlog sensor. It would be also nice to grab the endless spool groups by Spoolman. I mean there's a filament type and many spools of this type. It should be enough for the system to know that I have loaded 2 spools of White PLA to automatically group them together. Maybe with a confirmation dialog. It's also a possibility that grabbing info of remaining filament of the spool Happy Hare can switch from a spool with not enough filament to complete the object to a full one before starting the print.

**Comment by spitfire1337** [comment]
I've managed to get an implementation into happy hare for spoolman, including klipperscreen happy hare edition :) I'm going to test it for a few days and then try to figure out how to submit a pull request lol.

What I've done is added an additional state with spoolman ids, the spoolman system is only activated if the moonraker.conf has the [spoolman] entry. If the block exists, id's can be set by using mmu_set_gate_map spoolman={id}, this then gets referenced in the post_load macro (has to be there as we can't call the action_call_remote_method from within python, I tried) 

Then on the klipperscreen side, when you go to the filament management screen, if spoolman is enabled it will query for all non-archived spools and list them when you go to edit the gate. Selecting the spool will also change the material type & color. 

![mmu_set_gate_map](https://github.com/moggieuk/Happy-Hare/assets/1694700/1c08272d-8f65-4ace-be2f-52cc6bbbc019)
![Klipperscreen 1)](https://github.com/moggieuk/Happy-Hare/assets/1694700/6f7a857d-2ce3-4e0b-87b2-4ade6dccc58f)
![Klipperscreen 2](https://github.com/moggieuk/Happy-Hare/assets/1694700/e260274c-9d0f-44f6-9247-2a951c38200d)

**Comment by lettore** [comment]
> I've managed to get an implementation into happy hare for spoolman, including klipperscreen happy hare edition :) I'm going to test it for a few days and then try to figure out how to submit a pull request lol.
> 
> What I've done is added an additional state with spoolman ids, the spoolman system is only activated if the moonraker.conf has the [spoolman] entry. If the block exists, id's can be set by using mmu_set_gate_map spoolman={id}, this then gets referenced in the post_load macro (has to be there as we can't call the action_call_remote_method from within python, I tried)
> 
> Then on the klipperscreen side, when you go to the filament management screen, if spoolman is enabled it will query for all non-archived spools and list them when you go to edit the gate. Selecting the spool will also change the material type & color.
> 
> ![mmu_set_gate_map](https://user-images.githubusercontent.com/1694700/266975348-1c08272d-8f65-4ace-be2f-52cc6bbbc019.png) ![Klipperscreen 1)](https://user-images.githubusercontent.com/1694700/266976119-6f7a857d-2ce3-4e0b-87b2-4ade6dccc58f.png) ![Klipperscreen 2](https://user-images.githubusercontent.com/1694700/266976186-e260274c-9d0f-44f6-9247-2a951c38200d.png)

Great work.
It will be possible to insert directly the spool ID? I have many spools around and scrolling to find the right one it will be a tedious work.
In the future maybe it will be nice to use the QR code that can be printed by spoolman to directly load the correct data.

**Comment by FlorianWilk** [comment]
oh i guess i built something similar. I integrated Spoolman in HH:
1. adding a new ConfigProperty called gate_spool_id containing the SpoolmanIDs for each gate
2. extending select_and_load_spool and eject by notifying spoolman about the selected spool (-1 for eject)
3. extending KSHH by a new Panel which shows all of my used spools 
4. implementing a "stickyPanel" functionality, so i can show these overview on a secondary RPI/Touch replacing my paper labels i have on my dryBoxes
Maybe we should throw our stuff together? :)

![rn_image_picker_lib_temp_4ea9ae52-7f47-4074-b02c-c460a9159941](https://github.com/moggieuk/Happy-Hare/assets/3532286/219ec5b7-39b5-4b90-9b75-0abe958f977f)
![rn_image_picker_lib_temp_52ae7cf1-2c43-4ad8-af71-69a9f1deaa0e](https://github.com/moggieuk/Happy-Hare/assets/3532286/e39a9162-bbbb-40c9-84ba-c1d544958083)

**Comment by jwhite** [comment]
Has this already been included?  There is an enable spoolman config now...

Should this be closed?
