### ISSUE TITLE
Internal error during connect: No module named 'extras.mmu_leds'

### ISSUE THREAD

**Issue by leekinglai** [moggieuk/Happy-Hare#150]
just upgade to new version after popup this error
Internal error during connect: No module named 'extras.mmu_leds'

happy hare version v2.4.0-4-gb5c5cf4b

**Comment by ningpj** [comment]
ssh to the pi and run install.sh without arguments to update everything. 2.4 is a major update and needs to make changes to the config

**Comment by leekinglai** [comment]
problem solved, Thanks a lot
