### ISSUE TITLE
Install can't find home files on latest Klipper

### ISSUE THREAD

**Issue by jgbrown54** [moggieuk/Happy-Hare#165]
New install of latest Octoprint from Octoprint.org and Klipper from Klipper3d.org, can't find home directories.

Klipper config directory (/home/pixie/printer_data/config or /home/pixie/klipper_config) not found. Use '-c <dir>' option to override
pixie:Happy-Hare:% 

These folders do not exist after Klipper install. Klipper works fine from Octoprint.

printer.cfg is in /home/pixie  

pixie:~:% ls
ActivateFrontPanel.sh  OctoPrint
Happy-Hare             printer.cfg
klipper                Repetier-Server-1.4.2-Linux.deb
klippy-env             Repetier-Server-1.4.8-Linux.deb
mjpg-streamer          usbmount_0.0.24_all.deb
 
Installing on OrangePi Zero with armbian.

**Comment by moggieuk** [comment]
If you are logged in as the user "pixie", when you run the `./install.sh` script it will, by default, look in `/home/pixie/printer_data/config` for the klipper configuration and `/home/pixie/klipper` for the klipper install.  If you have installed into a different location you can specify with the `-c` and -`k` options to supply the alternative directory.

So it sounds like:
`./install.sh -c /home/pixie ......` maybe what you need but I've not seen an installation like this before..
