### ISSUE TITLE
MMU_LOAD_BYPASS not working

### ISSUE THREAD

**Issue by AMFkuna** [moggieuk/Happy-Hare#17]
Hi.
MMU_LOAD_BYPASS macro have bad gcode
should call the macro MMU_SELECT_BYPASS and MMU_LOAD

**Comment by moggieuk** [comment]
Thanks.  This is fixed to be:
MMU_LOAD EXTRUDER_ONLY=1

Don't want to combine with the select because there will unlikey be time to push the filament up to the extruder

**Comment by AMFkuna** [comment]
I mean in mmu_software.cfg

![Snímek obrazovky 2023-08-30 v 16 48 15](https://github.com/moggieuk/Happy-Hare/assets/17743216/8fca4b39-4c8c-4526-9c0c-60043ef72c4d)
