### ISSUE TITLE
Filametrix cut with restore position tries to return to 0,0 usually destroying pin located near there.

### ISSUE THREAD

**Issue by jwhite** [moggieuk/Happy-Hare#184]
Title pretty much says it all.

If you do a filametrix cut directly after power on, and are using restore position the toolhead attempts to return to 0,0.

Most people with cable chains are pultting the filametrix pin there, so it than attempts to remove said pin.

Pull request incoming.

**Comment by moggieuk** [comment]
Merged, but I did then rework to simply move the position saving to AFTER the optional homing to achieve the same thing.
