### ISSUE TITLE
Printing creates strange title in SpoolMan

### ISSUE THREAD

**Issue by jwhite** [moggieuk/Happy-Hare#186]
![image](https://github.com/moggieuk/Happy-Hare/assets/473577/9cd36f90-08ff-4f82-a21b-13ab07b33697)

Also I'm reasonably sure that the information about spools is already in the gcode, so it shouldn't be prompting me to select.

I am uploading the file then printing from fluidd (so that it is correctly parsed by happy hare.)

**Comment by moggieuk** [comment]
Hi! You are prolific at creating issues -- thank you!  You really should get involved in the plumbing and help evolve HH. :-)

Anyway, I'm not sure what you make of this. I'm struggling to parse the issue.  I just finished writing a doc page for spoolman with HH: https://github.com/moggieuk/Happy-Hare/blob/main/doc/spoolman_support.md

**Comment by jwhite** [comment]
This seems to have gone away, so marking closed.
