### ISSUE TITLE
Option 'step_pin' is not valid in section 'stepper_mmu_gear'

### ISSUE THREAD

**Issue by jgbrown54** [moggieuk/Happy-Hare#196]
Trying to set up Happy Hare with Repetier Server. Using FYSETC Enraged Rabbit Burrow. Managed to install using -c and -k options I think. But now I get an error Option 'step_pin' is not valid in section 'stepper_mmu_gear', Not sure how to proceed or what to check.

**Comment by moggieuk** [comment]
The installation wasn't successful.  I suspect you didn't get the "-c" directory correct or didn't restart Klipper.  This error occurs when the klipper modules have not been installed (as symlinks) into the klipper/klippy/extras directory

**Comment by moggieuk** [comment]
I’m going to close this issue as I’m confident it is simply a miss on the install

**Comment by mlauber** [comment]
> The installation wasn't successful. I suspect you didn't get the "-c" directory correct or didn't restart Klipper. This error occurs when the klipper modules have not been installed (as symlinks) into the klipper/klippy/extras directory

Ok so how do I fix this?  I had been running happy gare for a few weeks.  I just installed a Beacon sensor and now this error popped up.

**Comment by Luix333** [comment]
@moggieuk 
Hi, I'm getting the same error and I can see the symlinks in the extras directory

<img width="387" height="240" alt="Image" src="https://github.com/user-attachments/assets/ab5c34ec-c279-4573-8a2d-e2695803a912" />

<img width="426" height="110" alt="Image" src="https://github.com/user-attachments/assets/f63ba27f-a910-4a2a-88b4-33f7e00b4b72" />
