### ISSUE TITLE
minor issues in mmu_software.cfg

### ISSUE THREAD

**Issue by garyd9** [moggieuk/Happy-Hare#23]
Looking over the sample (commented out) _MMU_LOAD_SEQUENCE macros in mmu_software.cfg, it appears that some might be using the incorrect parameters.  For example, "_MMU_STEP_LOAD_BOWDEN MOVE={length}"  (I think the parameter should be "LENGTH" and not "MOVE").  Similar for other _MMU_STEP_LOAD_* calls.

**Comment by moggieuk** [comment]
Thanks!  Yes, looks like the doc isn't quite correct. I'll fix.

**Comment by moggieuk** [comment]
Fixed.
