### ISSUE TITLE
Internal error during connect: invalid syntax (mmu.py, line 5194)

### ISSUE THREAD

**Issue by rollduck** [moggieuk/Happy-Hare#236]
Good day,
After the last upate to v2.5.1-0-gb8093e28, the error "Internal error during connect: invalid syntax (mmu.py, line 5194)" occurred. Re-installing HH did not help. 
Best,
R.

**Comment by Maikaefer27** [comment]
Hello Happy-Hare team,
Unfortunately I also get this error ( invalid syntax (mmu.py, line 5194) ) after the update v2.5.1.
What further information do you need?
best regards

**Comment by moggieuk** [comment]
Fixed in latest patch.  It was a Python2 incompatibility but works now.   BTW At some point soon I'd recommend you upgrade your rpi / klipper to Python3 because Python 2 has been dead for 2 years now...
