### ISSUE TITLE
i don't understand why

### ISSUE THREAD

**Issue by salocain** [moggieuk/Happy-Hare#257]
the ercf logic is anytime strange.

the filament is loaded , hh know that ( ext 11 is loaded) the print ask change tool (T3)  (the servo cut the filament --> a option to use servo in cut macro could be great) unload fail ...for strange reason the unload is not great ... but ...the encoder didn't see move --> ok 

WHY if HH know the filament is  not unload he try to move the selector --> selector bloqued !! 
i configure retry --> but the selector in't aligned know !! and all is blocked !!

it's a mightmare --> HH know position etc ...but ....

**Comment by moggieuk** [comment]
I need to see `mmu.log` to understand.     If the encoder doesn't see any move and no other sensors are available to sense the filament position, HH probably has to be optimistic and assume the filament is clear of selector.

Anyway need `mmu.log` to help further.
