### ISSUE TITLE
Feature Request: outside cutter with a sensor 

### ISSUE THREAD

**Issue by zhangxiaokang7788** [moggieuk/Happy-Hare#260]
I make a outside  cutter just  behind my trad rack. It use a servo to cut filament,and a filament sensor to detect the filament.It use a small gap to discharge the cut filament.

I think happy hare can add a cutter like this. So I modified the code about unload gate（paste photo） and it can works.But I think this is not a good idea for i am a newer for code whrite. So, I’m beg for the implementation of this functionalitie. 

Thanks in advance.
![Snipaste_2024-04-07_14-01-05](https://github.com/moggieuk/Happy-Hare/assets/98631838/899bd062-6528-4797-b6de-35e2adf9e519)
![Snipaste_2024-04-07_14-01-30](https://github.com/moggieuk/Happy-Hare/assets/98631838/67d8f33f-4956-4f94-b30e-cb24001738ad)

**Comment by moggieuk** [comment]
Ok. I understand your need better.   You know this would be possible with custom unload sequence macros...

Have a read of this page: https://github.com/moggieuk/Happy-Hare/blob/main/doc/macro_customization.md#---_mmu_load_sequence--_mmu_unload_sequence-mmu_sequencecfg

You can turn on the macro version of the unload sequence (you can see the template).  Then you can copy and modify to accomplish what you want (you can use the `MMU_HOMING_MOVE` to move to your cutting position.

I don't have much time to help, but see if you can get started with this.  I know others have implemented custom unload logic using this...
