### ISSUE TITLE
Extruder microsteps

### ISSUE THREAD

**Issue by sanpedrox2** [moggieuk/Happy-Hare#29]
Hi, i just swapped from v1 to v2 (great work btw)

Now I seem to have an issue with my extruder motor. It seems like its stuck on 8 microsteps.

After changing to v2 and changing nothing else it started to sound weird, and I think its because of microstepping.

I am using extruder sync and dont have a tmc driver for E

**Comment by sanpedrox2** [comment]
Hi, thanks for answering :)

my extruder part from printer.cfg:

[extruder]
#step_pin: PD15
#dir_pin: PD14
#enable_pin: !PC7
#microsteps: 16
#rotation_distance: 33.600 #33.861
#full_steps_per_rotation: 200
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: PB3
sensor_type: ATC Semitec 104NT-4-R025H42G
sensor_pin: PA2
min_temp: 0
max_temp: 300
#pressure_advance = 0.1865
max_extrude_only_distance: 200
max_extrude_cross_section: 50.0

and mmu_hardware.cfg
[mmu_hardware.txt](https://github.com/moggieuk/Happy-Hare/files/12527974/mmu_hardware.txt)

**Comment by sanpedrox2** [comment]
the sound is most notable during retraction moves and when doing the cooling moves.
like it has a low pitched hum that im sure it didnt have before V2, kind of vibrates a little as well.

other than that, the software works great i might add, stellar work!

**Comment by moggieuk** [comment]
"homing the extruder" ... if the 'collision' method is used then yes it rams into extruder and tries to detect when there is no more movement.  This was a community idea that can work well if tuned.  Personally I use a reliable toolhead sensor so my bowden move ends just before hitting the extruder and then a civilized homing to the toolhead sensor.  I have an update that will make the collision detection a little more sensitive (will release soon) but it will
<img width="1031" alt="extruder_config_move" src="https://github.com/moggieuk/Happy-Hare/assets/32878385/f5b34575-843b-4c21-abef-e5730c06d30f">
 never be as good and having deterministic endstops.

On the extruder sound...
(side note): with the new magic '[mmu_config_setup]' you actually no longer need to comment out the step/dir/... settings under '[extruder]' - they will automatically be pulled into Happy Hare and nullified in '[extruder'].  Only the "tmc" part of the extruder definition needs to be moved (see pic). So `[manual_extruder_stepper extruder]' can be an empty section.

As for noise, I can't understand how you are getting away with this being commented:
#[tmc2209 manual_extruder_stepper extruder]
#uart_pin: E_TMCUART
#interpolate: true
#run_current: 0.55			# LDO 36STH20-1004AHG.  Match to macro below
#hold_current: 0.4
#sense_resistor: 0.110
#stealthchop_threshold: 0		# Spreadcycle (better for extruder)

This is the (tmc) driver part of the extruder and should exist in `mmu_hardware.cfg` and the equivalent commented in your `printer.cfg`.  I was looking at this to make sure you have your extruder motor settings to match your original..

Have a look at the picture and double check setup.  If is still an issue, send me your modified `mmu_hardware.cfg` again AND more of your `printer.cfg` -- i need to see both the '[extruder]' AND '[tmc...  extruder]' sections

**Comment by sanpedrox2** [comment]
i am getting away with the '[tmc... extruder]' part being commented out simply by not having a physical tmc driver stick for my extruder for the time being. its an older A4988 if i remember correctly. (running in standalone mode, and not using uart or spi)

if i set microsteps to 32 the sound goes back to normal, but i have been using it in 16 for a long time before i even built the ercf and havent had the sound before swapping to happy hare v2.

as for the homing... i have it set on collision for now.. but i do have a reliable toolhead sensor just below(after) the extruder gears. in v1 it was, as you describe it, "civilized". A fast move untils a few cm before extruder gear, then "sneak" in small increments towards and past extruder gear until sensor triggered. i cant seem to get that beahavior back in v2 (guess i dont understand what to change and where) i cant/wont use stallguard/touch for extruder

**Comment by moggieuk** [comment]
Ok. Lots of questions here and I'd rather use discord to chat about setup, but briefly:
1) Extruder sound - Happy Hare does nothing differently in stepper operation so suspect config change when moving definition to Happy Hare or it is the natural change of sound when synced.
2) For extruder homing methods it is all document in the README and drill down "configuration_reference".  If toolhead sensor is defined/configured and `extruder_force_homing` is False (default) it will use the toolhead sensor.  There is not need to "sneak in small increments to sensor" anymore -- it can home! I.e. one smooth movement.

Have a read of the load/unload sequences in the README and then reference the `mmu.log` and you will see each of the steps.
