### ISSUE TITLE
PAUSE halting above Print

### ISSUE THREAD

**Issue by Durahl** [moggieuk/Happy-Hare#306]
Unlike with the [Classic ERCF Client Macros](https://github.com/EtteGit/EnragedRabbitProject/blob/main/Klipper_Files/client_macros.cfg) the HappyHare one stops the Print right above the Part when a `PAUSE` command is being issued by the Slicer for say inserting some Magnets into the Print.

Can the `highlighted section` of the new HappyHare Pause Command be changed from
![Screenshot 2024-06-04 215456 copy2](https://github.com/moggieuk/Happy-Hare/assets/10585968/13a46aad-1c9d-4736-99cb-75e5f727dd95)
to the Classic ERCF one without breaking something?
![Screenshot 2024-06-04 215456 copy](https://github.com/moggieuk/Happy-Hare/assets/10585968/7c40d95f-e3ab-4450-ba56-de1a0c05bc03)

I assume the ( Line 55 ) `_PARK Z_HOP=5` in the HappyHare one will be taken care of by the ( Line 65 ) `G1 Z{z_safe} F900` and the Code Snippet at the beginning? 🤔

On a somewhat related issue... My Tool head will have lost all pressure when resuming the Print usually resulting in a visible Gap in the Outer Perimeters - Is there something that can be done about this via the Resume Command? The Macro does mention a _"Good place to add other things like purging or nozzle cleaning"_ but what should one put in there? 🤨

**Comment by moggieuk** [comment]
Looks like you are running an older version of Happy Hare. If you update you will see there is much more control now and you can specify a park position.
