### ISSUE TITLE
Does it work well for you?

### ISSUE THREAD

**Issue by Ecaze81** [moggieuk/Happy-Hare#315]
I've been trying to use the ercf V1 improve for a few weeks now... and it remains very complicated.
Can you make complete figurines?
Personally I can do little things like hueforge, but if I want to make a figurine with a lot of changes it always messes up at some point, and when the problems start... it doesn't stop.
Load / unload which is not done well
Cutter that cuts before removing the filament
filament not fully charging etc etc.
how does it work for you?
Improvement: EREC // Springy // Binky

**Comment by moggieuk** [comment]
This is the wrong place to ask.   Try the ERCF builder forum: https://discord.com/channels/460117602945990666/909743915475816458
