### ISSUE TITLE
MMU_TEST_CONFIG does not allow changing bowden length variable

### ISSUE THREAD

**Issue by hadesz** [moggieuk/Happy-Hare#322]
Due to inconsistent naming, MMU_TEST_CONFIG identifies MMU_CALIBRATION_BOWDEN_LENGTH as invalid parameter, blocking users to fine-tune bowden length parameter.

(Pull req with a fix is incoming...)

**Comment by moggieuk** [comment]
Good catch. This was due to an additon to try to spot and give feedback for invalid parameters.

**Comment by moggieuk** [comment]
Thanks for the PR.  This is the one naming exception. I was tempted to change the variable name but I think your PR is good for now.

**Comment by hadesz** [comment]
I did also consider that option, even the argument rename to match
convention of the rest, but due to the lack of tests, I chose the least
risky option...
