### ISSUE TITLE
Cannot get Easy board to flash. 

### ISSUE THREAD

**Issue by utzy79** [moggieuk/Happy-Hare#326]
Hi . I am having alot of trouble flashing my Easybrd. Keeps coming up with the attached error.
![Screenshot 2024-06-29 124959](https://github.com/moggieuk/Happy-Hare/assets/45909092/02cdc659-93fc-4761-b560-92a1a984953c)
![image](https://github.com/moggieuk/Happy-Hare/assets/45909092/643312f9-fa67-4ec0-8888-27b80f3acd69)

**Comment by moggieuk** [comment]
Hi!  This really isn't the place to get support/help for mmu flashing.  I'd highly recommend the ercf-questions channel on the Voron Discord: 
https://discord.com/channels/460117602945990666/909743915475816458

**Comment by utzy79** [comment]
Threw the board in the bin and bought a new main board instead.
