### ISSUE TITLE
Possible to run an extra command when the MMU errors?

### ISSUE THREAD

**Issue by yourbuddydinec** [moggieuk/Happy-Hare#329]
I have a TTS and audio player command on my printer and hoped I could run one of those commands whenever an error happens so I can notice it easier. 

Is this at all possible?

**Comment by moggieuk** [comment]
You can do it already :-)

```yml
pause_macro: PAUSE
```
Change PAUSE to say "MY_PAUSE".  In  MY_PAUSE, call the audio player and then call the real PAUSE.

Another way would be to add a macro to:
```yml
variable_user_print_state_changed_extension : ''
```
This macro would need to check to a change to the mmu_paused print state and if detected play the tune.
Read here for states: https://github.com/moggieuk/Happy-Hare/wiki/Print-Job-State-Machine#---job-state-transitions
