### ISSUE TITLE
Question regarding Machine start G-Code

### ISSUE THREAD

**Issue by Durahl** [moggieuk/Happy-Hare#331]
Is it safe to assume that the Print Start Code ( highlighted in the Screenshot )...
![Screenshot 2024-07-01 195307](https://github.com/moggieuk/Happy-Hare/assets/10585968/acb5366c-6f7e-4c5c-b884-6f301fc9b9ea)
...NEEDS to be one line and CANNOT be made more readable by splitting it up into one line per Stat? 🤔

Just wondering because when I made the Change from:
`MMU_START_SETUP INITIAL_TOOL={initial_tool} REFERENCED_TOOLS=!referenced_tools! TOOL_COLORS=!colors! TOOL_TEMPS=!temperatures! TOOL_MATERIALS=!materials! PURGE_VOLUMES=!purge_volumes!`

to

`MMU_START_SETUP`
`INITIAL_TOOL={initial_tool}`
`REFERENCED_TOOLS=!referenced_tools!`
`TOOL_COLORS=!colors!`
`TOOL_TEMPS=!temperatures!`
`TOOL_MATERIALS=!materials!`
`PURGE_VOLUMES=!purge_volumes!`

( among others ) the Colors from the Slicer would no longer get parsed to the Slicer 🤨

**Comment by ningpj** [comment]
Yes, they are arguments passed to the macro so all need to be on the same line
