### ISSUE TITLE
Extruder sync during MMU_CALIBRATE_BOWDEN

### ISSUE THREAD

**Issue by demitrix** [moggieuk/Happy-Hare#342]
My system uses the extruder gear separation due to loaded filament for the extruder_sensor. This leads to problems when trying to run MMU_CALIBRATE_BOWDEN as the sensor fails to trigger. Being able to sync the extruder, even for the last 10-20mm would resolve this issue.

**Comment by moggieuk** [comment]
So if I understand the needed logic, it would be:
IF extruder_sensor is being used for bowden homing:
   THEN spin extruder whilst finding the homing spot
   (would need to be done in calibration and on regular load)
   

Another thing to consider:
Given the location of your sensor, why not configure as a toolhead sensor?  I actually think you would get more benefit from this for a number of reasons.  Then the initial calibration can use collision detection (it is only done one time and frankly you can tweak the number by hand by editing `mmu_vars.cfg` once you get in the ballpark.  The homing to "toolhead sensor" is always done with synced extruder.  Assuming you have reliable fast bowden moves, you can completely turn off the need for extruder homing by setting "extruder_homing_endstop: none".   This will cause HH to do a fast bowden move the end of the bowden (or close to it), then home to the toolhead sensor (max distance of `toolhead_homing_max`) using synced extruder move.  I know others that have this setup.
