### ISSUE TITLE
MMU_COLD_PULL PLA Hot Temp seems overly high - 250c

### ISSUE THREAD

**Issue by ningpj** [moggieuk/Happy-Hare#346]
MMU_COLD_PULL works really well (ABS). However the PLA/PETG hot_temp's seems too high and are currently set to 250c in the table...shouldn't this be more like 190-200c?  
```
    {% set materials = {
        'NYLON': {'hot_temp': 260, 'cold_temp': 50, 'pull_temp': 120, 'min_extrude_temp': 190},
        'PLA':   {'hot_temp': **250**, 'cold_temp': 45, 'pull_temp': 100, 'min_extrude_temp': 160},
        'ABS':   {'hot_temp': 255, 'cold_temp': 50, 'pull_temp': 120, 'min_extrude_temp': 190},
        'PETG':  {'hot_temp': **250**, 'cold_temp': 45, 'pull_temp': 100, 'min_extrude_temp': 180}
    } %}
```
I haven't tested it with anything other than ABS and are happy if its been validated.

**Comment by moggieuk** [comment]
It was set high to ensure that any higher temp filament is also purged.  It is for a short time so should be ok.  Happy to accept feedback though.
