### ISSUE TITLE
Duplicate chip name 'tmc2209_extruder'

### ISSUE THREAD

**Issue by kolbenhans** [moggieuk/Happy-Hare#35]
Immediately after the installation, I first had the error:
##########################################
`Shared TMC uarts need unique address or select_pins polarity

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted`
###########################################
This was caused by the same variable name "E_TMCUART" used by HH2 and my own configuration (easy fix)

---------------------------------------

After i solved this: i now have the following error message:
Duplicate chip name 'tmc2209_extruder'

Klippy log part: 
#########################################
MMU Info: Automatically moved config option 'step_pin' from '[extruder]' config section to '[manual_extruder_stepper extruder]'
MMU Info: Automatically moved config option 'dir_pin' from '[extruder]' config section to '[manual_extruder_stepper extruder]'
MMU Info: Automatically moved config option 'enable_pin' from '[extruder]' config section to '[manual_extruder_stepper extruder]'
MMU Info: Automatically moved config option 'rotation_distance' from '[extruder]' config section to '[manual_extruder_stepper extruder]'
MMU Info: Automatically moved config option 'microsteps' from '[extruder]' config section to '[manual_extruder_stepper extruder]'
MMU Info: Automatically moved config option 'full_steps_per_rotation' from '[extruder]' config section to '[manual_extruder_stepper extruder]'
MMU Info: Automatically moved config option 'pressure_advance' from '[extruder]' config section to '[manual_extruder_stepper extruder]'
Config error
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 141, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/pi/klipper/klippy/klippy.py", line 130, in load_object
    self.objects[section] = init_func(config.getsection(section))
  File "/home/pi/klipper/klippy/extras/tmc2209.py", line 102, in load_config_prefix
    return TMC2209(config)
  File "/home/pi/klipper/klippy/extras/tmc2209.py", line 67, in __init__
    tmc.TMCVirtualPinHelper(config, self.mcu_tmc)
  File "/home/pi/klipper/klippy/extras/tmc.py", line 487, in __init__
    ppins.register_chip("%s_%s" % (name_parts[0], name_parts[-1]), self)
  File "/home/pi/klipper/klippy/pins.py", line 129, in register_chip
    raise error("Duplicate chip name '%s'" % (chip_name,))
error: Duplicate chip name 'tmc2209_extruder'
webhooks client 3040183320: New connection
webhooks client 3040183320: Client info {'program': 'Moonraker', 'version': 'v0.8.0-138-gfe12095'}
########################

I have no Idea how to solve this

regards

**Comment by kolbenhans** [comment]
My issue with "copy" TMC extruder values and not "move"....

...working fine now ....

**Comment by rwijnhov** [comment]
How did you fix this?
