### ISSUE TITLE
Internal Error on Command: "SET_LED_EFFECT"

### ISSUE THREAD

**Issue by justinr54321** [moggieuk/Happy-Hare#368]
Setting up a chain of LEDs from the board to the ERCT LEDs, then to the Apron LEDs, and I get the error mentioned above. Klippy log shows it to be an issue with the python files. Showing no errors in the MMU log.
[Log Files.zip](https://github.com/user-attachments/files/16473201/Log.Files.zip)
![image](https://github.com/user-attachments/assets/c4bc4ede-3c7c-4c3c-9be3-597368768432)
When I comment out the exit range, no issues except for no Apron LEDs.

**Comment by moggieuk** [comment]
I'd recommend a lower frame rate: the default 24 is already very high.
What does this section look like:
```
[neopixel mmu_leds]
pin: mmu:MMU_NEOPIXEL
chain_count: 18                        # Number gates x1 or x2 + 1 (if you want status)
color_order: GRBW  
```

**Comment by justinr54321** [comment]
> What does this section look like:
> 
> ```
> [neopixel mmu_leds]
> pin: mmu:MMU_NEOPIXEL
> chain_count: 16                        # Number gates x1 or x2 + 1 (if you want status)
> color_order: GRBW  
> ```
> 
> I wonder if you LED chain isn't long enough.. would need to be at least 16 LEDs.
> 
> Also, make sure your klipper-led_effects module is up-to-date because the failure is coming from within that module.

Thank you. I forgot to change it from 8 to 16. And is now working. 🤦‍♂️

**Comment by moggieuk** [comment]
Cool!
