### ISSUE TITLE
Sync_unload_extruder

### ISSUE THREAD

**Issue by MilosMrihlad** [moggieuk/Happy-Hare#375]
Hi, I want to ask if there is any way to enable sync_unload_extruder. I am currently using sync_to_extruder, and sync_for_tip. It helps ercf when unloading the filament, but then switches servos when it goes to full unload, and I would need ercf to help it immediately. Because the filament needs to be unloaded right away. Is there any way to do this or where to set it up. Thank you

**Comment by moggieuk** [comment]
You can't force syncing during the entire unload operation but it will remain synced during tip forming if you have `sync_form_tip: 1`.

Moves during the unload that can be synced already are, but some must be done unsynced.  One that is important is the final ejecting.  If synced, errors can cause the filament to eject too far.  Using just the extruder stepper avoids this for example.
