### ISSUE TITLE
MMU Sync Gear needs home first to engage

### ISSUE THREAD

**Issue by mochoandre** [moggieuk/Happy-Hare#377]
Hello,
In HH 2.60
If you have MMU sync Gear enabled, If MMU is not homed, despite it's does not throwing any error,  when you specially Call "MMU_SYNC_GEAR_MOTOR SYNC=1" it does not engage.

For clarity I think it should say that is not homed or automatically home.
I think this is mostly important to testing purposes. In "normal" operation I think it's not noticeble.

Best regards aad thank you very much

**Comment by moggieuk** [comment]
Thanks. Yes, there should be an error so the user knows it hasn't synced...
