### ISSUE TITLE
EREC Cutter tune Servo

### ISSUE THREAD

**Issue by mochoandre** [moggieuk/Happy-Hare#379]
MMU_SERVO SERVO=CUT_SERVO ANGLE=70

Moves gate Servo. How can I tune EREC cutter servo angle. Mine does not look like it wants to go open position

**Comment by mochoandre** [comment]
If Someone have the same problem the trick is to move through web interface to open position ( or close, i'm not shure), umount the cutting servo, put the cutting arm in the phiscally desired position, mount motor again and after that tune angles in software.

**Comment by moggieuk** [comment]
You can use:
```
SET_SERVO SERVO=cut_servo ANGLE=...
```
To test positions.  Once you have it correct, update `mmu_erec_cutter.cfg`
