### ISSUE TITLE
fix old version klipper

### ISSUE THREAD

**Issue by checkitog** [moggieuk/Happy-Hare#381]
friend, to make it work with old versions of klipper like the one my sovol sv08 has, I have to modify mmu_toolhead.py replacing this: 

```# The following aren't very interesting for MMU control so leave to klipper defaults min_cruise_ratio = 0.5 if config.getfloat ('minimum_cruise_ratio', None) is None: req_accel_to_decel = config.getfloat('max_accel_to_decel', None, above=0.) if req_accel_to_decel is not None: config.deprecate('max_accel_to_decel') min_cruise_ratio = 1. - min(1. , (req_accel_to_decel / self.max_accel)) self.min_cruise_ratio = config.getfloat('minimum_cruise_ratio', min_cruise_ratio, below=1., minval=0.) self.square_corner_velocity = config.getfloat('square_corner_velocity', 5., minval=0.) self.junction_deviation = self.max_accel_to_decel = 0. self._calc_junction_deviation() self.requested_accel_to_decel = req_accel_to_decel # Backward compatibility for old klipper & Sovol SV 04 IDEX Printer ```

for this other thing:

``` # The following aren't very interesting for MMU control so leave to klipper defaults self.requested_accel_to_decel = config.getfloat('max_accel_to_decel', self.max_accel * 0.5, above=0.) self.max_accel_to_decel = self.requested_accel_to_decel self.square_corner_velocity = config.getfloat('square_corner_velocity', 5., minval=0.) self.junction_deviation = 0. ```

could you fix it?

**Comment by moggieuk** [comment]
Can you create a PR for the change so I can review.  If would need a condition to detect when to make the change.

**Comment by checkitog** [comment]
I don't understand, what do you want me to do?

**Comment by k1-801** [comment]
I believe the fix #388 for Creality printers (which also have an old version of Klipper) could resolve this.

**Comment by moggieuk** [comment]
Can you see it this has been fixed in latest push.  I added support some some older version of klipper...

**Comment by checkitog** [comment]
Just updated happy-here, got no errors, seems to be working fine, thanks for your great work!
