### ISSUE TITLE
Problem with Both Toolhead Sensor

### ISSUE THREAD

**Issue by MattiaFontanaErrepinet** [moggieuk/Happy-Hare#387]
Hi, if both sensor is on State Open klipper not start with this error. 
Only on start up/reboot. 
But if one of sensor is triggered working fine. 

`MCU 'mmu' shutdown: Timer too close
This often indicates the host computer is overloaded. Check
for other processes consuming excessive CPU time, high swap
usage, disk errors, overheating, unstable voltage, or
similar system problems on the host computer.
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown
`

**Comment by moggieuk** [comment]
TTC is an error that can always occur.  In the very latest patch to the current v2.7.0 release I have added TTC mitigation for all the places that were tripping users up.  It isn't possible to "fix" this error completely -- Klipper is based on precise timings  and any little glitch or pause can cause this.

That said, the latest code base solves 90% of the TTC cases I have investigated.
