### ISSUE TITLE
Fysetc ERB V2.0 wrong pin assignment using ./install.sh -i

### ISSUE THREAD

**Issue by npa62** [moggieuk/Happy-Hare#401]
When using ./install.sh -i, MMU_GEAR_UART is assigned to gpio20, which according to Fysetc's own documentation should be gpio11.

**Comment by moggieuk** [comment]
Which version of the board is this?  v1 or v2?

I'm sure the v1 board is gpio20 because that's what I'm using.

**Comment by npa62** [comment]
That's a V2.



________________________________
Fra: moggieuk ***@***.***>
Sendt: 29. august 2024 18:24
Til: moggieuk/Happy-Hare ***@***.***>
Cc: npa62 ***@***.***>; Author ***@***.***>
Emne: Re: [moggieuk/Happy-Hare] Fysetc ERB V2.0 wrong pin assignment using ./install.sh -i (Issue #401)


Which version of the board is this? v1 or v2?

I'm sure the v1 board is gpio20 because that's what I'm using.

**Comment by moggieuk** [comment]
Thanks.  It's fixed in my staging branch for next update.

**Comment by npa62** [comment]
Sounds great. You're a champ.



________________________________
Fra: moggieuk ***@***.***>
Sendt: 29. august 2024 19:17
Til: moggieuk/Happy-Hare ***@***.***>
Cc: npa62 ***@***.***>; Author ***@***.***>
Emne: Re: [moggieuk/Happy-Hare] Fysetc ERB V2.0 wrong pin assignment using ./install.sh -i (Issue #401)


Thanks. It's fixed in my staging branch for next update.
