### ISSUE TITLE
No gates found for tool 0 

### ISSUE THREAD

**Issue by MDegelmann** [moggieuk/Happy-Hare#403]
I always get this error message

MMU issue detected. Print will be paused
Reason: Error during automapping
No gates found for tool 0 with Color 00ff00

**Comment by AcrimoniousMirth** [comment]
> I always get this error message
> 
> MMU issue detected. Print will be paused Reason: Error during automapping No gates found for tool 0 with Color 00ff00

Sorry to comment on an old thread and issue, what was the fix?
