### ISSUE TITLE
Broken Images in slicer settings wiki page

### ISSUE THREAD

**Issue by T-509** [moggieuk/Happy-Hare#423]
The problem is not that there are broken images, it's that the description are useless without  them. For example "check the boxes as shown" but because there is no images so you don't know what the settings are that need to be changed.  

![image-2](https://github.com/user-attachments/assets/df6be768-141e-4760-856f-b06d7f0a54c3)

**Comment by moggieuk** [comment]
The images are all there.  Try this link: [https://github.com/moggieuk/Happy-Hare/wiki/Slicer-Setup](https://github.com/moggieuk/Happy-Hare/wiki/Slicer-Setup)

Github wiki gets confused if you use browser forward or back buttons. Use just the side bar navigation and try refreshing page if you see this.

**Comment by T-509** [comment]
Strange, I've tried multiple browsers, mobile and desktop with the direct link, and 2 different computers on different networks, each come up with the same error,  inspect  returns with "406 (not acceptable)" . Which I think is client side but I'm not familiar enough, clearing cache doesn't seem to help either.  Maybe I'm just unlucky.

**Comment by T-509** [comment]
cloning the wiki locally seemed to pull the images correctly wish I though of doing it earlier.
