### ISSUE TITLE
add a configuration to set filament_pos behind the extruder gear after independent tip forming

### ISSUE THREAD

**Issue by jacksky6** [moggieuk/Happy-Hare#432]
Can there add a configuration?

When there is no sensor on the toolhead, after independent tip forming, the filament is assumed to be behind the extruder gear (or known by calculation), and then proceed to the following operations. 

At present, it seems that extruder(only use) needs to be retracted 15mm to determine the position of the filament through the encoder detection. For users with a long material tube and a belay sync buffer installed, it is easy to get an error here.

When the pipe resistance is large, it is not desirable to use the extruder alone.

**Comment by moggieuk** [comment]
Nice to see someone reading the code :-).  I assume you mean this logic:
```
    # Retract the filament by the extruder stepper only and see if we do not have any encoder movement
    # This assumes that we already tip formed, and the filament is parked somewhere in the extruder
    # Return if filament detected and distance filament moved during test
    def _test_filament_in_extruder_by_retracting(self, length=None):
```
 Unfortunately without toolhead sensor there is no other way I can think of to validate if filament was present or not and you are correct the variability that Belay adds to the bowden is a concern.  Really a toolhead sensor is HIGHLY recommended.  That said, there are two things you can try:
1. The 15mm is set by a parameter that is not exposed:
```
encoder_move_step_size: 15
```
You can increase this a little. I think 20 or 21 wouldn't cause issues.  Note that if you are using the encoder to park you cannot go too large.  If on a Tradrack and you have a gate sensor you can increase a little more I think (honestly not tested).
2. The encoder based validation can be disabled by setting:
```
encoder_move_validation: 0
```
This turns of a couple of checks that start to be a problem with longer bowden tubes (or Belay slack).
