### ISSUE TITLE
3D Chameleon support 

### ISSUE THREAD

**Issue by Firas95k** [moggieuk/Happy-Hare#436]
[Chameleon Macros.txt](https://github.com/user-attachments/files/17088959/Chameleon.Macros.txt)

I have a modified 3D Chameleon filament changer system using directly connected stepper drivers to my main board, it is awesome that it is simple and reliable way to do multiple filaments.... Advantages/Differences is that it does not need a servo and the gear stepper direction is reversed for T2 & T3 (T1&T2 is the same direction as the extruder), would be really awesome if it was supported.

If possible any guide of which files to change to make that work would help us immensely.

Below are some macros crafted for homing and manual loading all the filaments to the Y-Splitter (Y junction were the filament is parked)

**Comment by Firas95k** [comment]
[gcode_macro CHAMELEON_HOME]
description: homes the tool selector.
variable_ysplit_extruder: 1120
variable_chameleon_ysplit: 100
variable_chameleon_speed: 300
variable_chameleon_acc: 100
variable_extrude_amount: 120
variable_chameleon_is_homed: 0
gcode:
  {% set svv = printer.save_variables.variables %}
  # Initialize or update the chameleon parameter
  {% if 'chameleon' not in svv %}
    {% set chameleon = [0, -1, 'empty', 'empty', 'empty', 'empty', -1] %}
  {% else %}
    {% set chameleon = svv.chameleon %}
    {% if chameleon[0] != -1 %}
      {% set chameleon = [chameleon[0]] + [chameleon[0]] + chameleon[2:] %}   #set previous=current
    {% else %}
      {% set chameleon = [chameleon[0]] + chameleon[1:] %}             #preserve previous state if current=-1 
    {% endif %}
  {% endif %}
  MANUAL_STEPPER STEPPER=selector SET_POSITION=0 
  MANUAL_STEPPER STEPPER=selector MOVE=-2.65 STOP_ON_ENDSTOP=1
  MANUAL_STEPPER STEPPER=selector SET_POSITION=0 
  MANUAL_STEPPER STEPPER=selector MOVE=0.12
  MANUAL_STEPPER STEPPER=selector SET_POSITION=0 
  # Set current tool to 0 after homing
  {% set chameleon = [0] + chameleon[1:] %}
  SAVE_VARIABLE VARIABLE=chameleon VALUE="{chameleon}"
  SET_GCODE_VARIABLE MACRO=CHAMELEON_HOME VARIABLE=chameleon_is_homed VALUE=1
  M118 Chameleon is Homed!
  CHAMELEON_CHK_ACTIVE_TOOL

[gcode_macro CHAMELEON_TS0]
gcode:
  _TOOL_SELECT TOOL=0
  CHAMELEON_CHK_ACTIVE_TOOL

[gcode_macro CHAMELEON_TS1]
gcode:
  _TOOL_SELECT TOOL=1
  CHAMELEON_CHK_ACTIVE_TOOL

[gcode_macro CHAMELEON_TS2]
gcode:
  _TOOL_SELECT TOOL=2
  CHAMELEON_CHK_ACTIVE_TOOL

[gcode_macro CHAMELEON_TS3]
gcode:
  _TOOL_SELECT TOOL=3
  CHAMELEON_CHK_ACTIVE_TOOL

[gcode_macro _TOOL_SELECT]
gcode:
  {% set TOOL = params.TOOL|int %}
  {% if printer["gcode_macro CHAMELEON_HOME"].chameleon_is_homed != 1 or printer.stepper_enable.steppers['manual_stepper selector'] != True %}
    M118 Chameleon is not homed, must run CHAMELEON_HOME
  {% else %}
    {% set svv = printer.save_variables.variables %}
    {% set chameleon = svv.chameleon %}
    {% set chameleon = [TOOL, chameleon[0]] + chameleon[2:] %}
    {% if TOOL == 0 %}
      MANUAL_STEPPER stepper=selector MOVE=0
    {% elif TOOL == 1 %}
      MANUAL_STEPPER stepper=selector MOVE=0.5
    {% elif TOOL == 2 %}
      MANUAL_STEPPER stepper=selector MOVE=1.0
    {% elif TOOL == 3 %}
      MANUAL_STEPPER stepper=selector MOVE=1.5
    {% endif %}
    SAVE_VARIABLE VARIABLE=chameleon VALUE="{chameleon}"
    M118 Chameleon is set to tool {TOOL}
  {% endif %}

[gcode_macro CHAMELEON_TOOL_FREE]
description: Free filament path from selector and disable the motors
gcode:
  {% if printer["gcode_macro CHAMELEON_HOME"].chameleon_is_homed != 1 or printer.stepper_enable.steppers['manual_stepper selector'] != True %}
    M118 Chameleon is not homed, must run CHAMELEON_HOME
  {% else %}
    {% set svv = printer.save_variables.variables %}
    {% set chameleon = svv.chameleon %}
    {% set TOOL = chameleon[0] %}    
    # Update chameleon parameter
    {% set chameleon = [-1, TOOL] + chameleon[2:] %}
    SAVE_VARIABLE VARIABLE=chameleon VALUE="{chameleon}"    
    M118 Chameleon free filament path for tool {TOOL}
    {% if TOOL == 0 %}
      MANUAL_STEPPER stepper=selector MOVE=1 
    {% elif TOOL == 1 %}
      MANUAL_STEPPER stepper=selector MOVE=1.5
    {% elif TOOL == 2 %}
      MANUAL_STEPPER stepper=selector MOVE=0
    {% elif TOOL == 3 %}
      MANUAL_STEPPER stepper=selector MOVE=0.5
    {% endif %}
    MANUAL_STEPPER STEPPER=selector ENABLE=0               #disables steppers
    SET_STEPPER_ENABLE STEPPER="extruder_stepper chameleon" ENABLE=0
    SET_GCODE_VARIABLE MACRO=CHAMELEON_HOME VARIABLE=chameleon_is_homed VALUE=0
  {% endif %}
  CHAMELEON_CHK_ACTIVE_TOOL

[gcode_macro CHAMELEON_Y_UNLOAD]
description: Unloads the filament from the Y-splitter and updates tip shaping requirements
gcode:
  {% set svv = printer.save_variables.variables %}
  {% set chameleon = svv.chameleon %}
  {% set TOOL = chameleon[0] %}
  {% set YSPLIT_DIST = printer["gcode_macro CHAMELEON_HOME"].chameleon_ysplit %}
  {% set SPEED = printer["gcode_macro CHAMELEON_HOME"].chameleon_speed %}
  {% set ACC = printer["gcode_macro CHAMELEON_HOME"].chameleon_acc %}

  # Check if there's filament loaded in the current tool
  {% if chameleon[TOOL+2] == 'empty' %}
    M118 Tool {TOOL} is already empty. No unload necessary.
  {% else %}
    # Check if the system is homed
    {% if printer["gcode_macro CHAMELEON_HOME"].chameleon_is_homed != 1 or printer.stepper_enable.steppers['manual_stepper selector'] != True %}
      M118 Chameleon is not homed, must run CHAMELEON_HOME
    {% else %}
      # Perform unload operation
      {% set MOVE_DISTANCE = -(YSPLIT_DIST+30) if TOOL == 0 or TOOL == 1 else (YSPLIT_DIST+30) %}
      FORCE_MOVE STEPPER="extruder_stepper chameleon" DISTANCE={MOVE_DISTANCE} VELOCITY={SPEED} ACCEL={ACC}
      
      # Update the tool status to 'empty'
      {% set chameleon = chameleon[:TOOL+2] + ['empty'] + chameleon[TOOL+3:6] + [chameleon[6]] %}
      SAVE_VARIABLE VARIABLE=chameleon VALUE="{chameleon}"
      M118 Unload tool {TOOL} from Y-splitter by {YSPLIT_DIST+30}mm and set status to 'empty' for tool {TOOL}
    {% endif %}
  {% endif %}
  CHAMELEON_CHK_ACTIVE_TOOL

[gcode_macro CHAMELEON_LOAD_HARD]
description: Loads the normal hard filament into the Y-splitter and updates tip shaping requirements
gcode:
  {% set svv = printer.save_variables.variables %}
  {% set chameleon = svv.chameleon %}
  {% set TOOL = chameleon[0] %}
  {% set YSPLIT_DIST = printer["gcode_macro CHAMELEON_HOME"].chameleon_ysplit %}
  {% set SPEED = printer["gcode_macro CHAMELEON_HOME"].chameleon_speed %}
  {% set ACC = printer["gcode_macro CHAMELEON_HOME"].chameleon_acc %}

  # Check if the tool is already loaded or if its status conflicts
  {% if chameleon[TOOL+2] == 'hard' %}
    M118 Error: Tool {TOOL} is already loaded with hard filament. Please unload it first.
  {% elif chameleon[TOOL+2] == 'soft' %}
    M118 Error: Tool {TOOL} is already loaded with soft filament. Please unload it first.
  {% else %}
    {% if printer["gcode_macro CHAMELEON_HOME"].chameleon_is_homed != 1 or printer.stepper_enable.steppers['manual_stepper selector'] != True %}
      M118 Chameleon is not homed, must run CHAMELEON_HOME
    {% else %}
      # Update the tool status to 'hard'
      {% set chameleon = chameleon[:TOOL+2] + ['hard'] + chameleon[TOOL+3:6] + [chameleon[6]] %}
      SAVE_VARIABLE VARIABLE=chameleon VALUE="{chameleon}"
      {% set MOVE_DISTANCE = YSPLIT_DIST if TOOL == 0 or TOOL == 1 else -YSPLIT_DIST %}
      FORCE_MOVE STEPPER="extruder_stepper chameleon" DISTANCE={MOVE_DISTANCE} VELOCITY={SPEED} ACCEL={ACC}
      M118 Load tool {TOOL} to Y-splitter by {YSPLIT_DIST}mm and set status to 'hard' for tool {TOOL}
    {% endif %}
  {% endif %}
  CHAMELEON_CHK_ACTIVE_TOOL

[gcode_macro CHAMELEON_LOAD_SOFT]
description: Loads soft TPU filament into the Y-splitter and updates tip shaping requirements
gcode:
  {% set svv = printer.save_variables.variables %}
  {% set chameleon = svv.chameleon %}
  {% set TOOL = chameleon[0] %}
  {% set YSPLIT_DIST = printer["gcode_macro CHAMELEON_HOME"].chameleon_ysplit %}
  {% set SPEED = printer["gcode_macro CHAMELEON_HOME"].chameleon_speed %}
  {% set ACC = printer["gcode_macro CHAMELEON_HOME"].chameleon_acc %}

  # Check if the tool is already loaded or if its status conflicts
  {% if chameleon[TOOL+2] == 'hard' %}
    M118 Error: Tool {TOOL} is already loaded with hard filament. Please unload it first.
  {% elif chameleon[TOOL+2] == 'soft' %}
    M118 Error: Tool {TOOL} is already loaded with soft filament. Please unload it first.
  {% else %}
    {% if printer["gcode_macro CHAMELEON_HOME"].chameleon_is_homed != 1 or printer.stepper_enable.steppers['manual_stepper selector'] != True %}
      M118 Chameleon is not homed, must run CHAMELEON_HOME
    {% else %}
      # Update the tool status to 'soft'
      {% set chameleon = chameleon[:TOOL+2] + ['soft'] + chameleon[TOOL+3:6] + [chameleon[6]] %}
      SAVE_VARIABLE VARIABLE=chameleon VALUE="{chameleon}"
      {% set MOVE_DISTANCE = YSPLIT_DIST if TOOL == 0 or TOOL == 1 else -YSPLIT_DIST %}
      FORCE_MOVE STEPPER="extruder_stepper chameleon" DISTANCE={MOVE_DISTANCE} VELOCITY={SPEED} ACCEL={ACC}
      M118 Load tool {TOOL} to Y-splitter by {YSPLIT_DIST}mm and set status to 'soft' for tool {TOOL}
    {% endif %}
  {% endif %}
  CHAMELEON_CHK_ACTIVE_TOOL

[gcode_macro CHAMELEON_CHK_ACTIVE_TOOL]
gcode:
  {% set svv = printer.save_variables.variables %}
  {% set chameleon = svv.chameleon %}
  RESPOND TYPE=command MSG='Current active tool is tool {chameleon[0]}'
  RESPOND TYPE=command MSG='Previous active tool was tool {chameleon[1]}'
  RESPOND TYPE=command MSG='Tool status:'
  {% for tool in range(4) %}
    RESPOND TYPE=command MSG='Tool {tool}: {chameleon[tool+2]}'
  {% endfor %}
  RESPOND TYPE=command MSG='Tool loaded to extruder: {chameleon[6]}'

**Comment by moggieuk** [comment]
There is a user that modified HH to work with Chameleon (or something like it).  It requires getting in pretty deep with the code to do that kind of change.

I'm currently have prototype multi-stepper support (I call in type-B mmu) but I don't have Chameleon or sponsorship so I'm unlikely to get to this any time soon..

**Comment by u3dreal** [comment]
I get an error downloading the macros .. can you reupload please ?
I also hacked my version to work via a second  controller via clipper.
Would be interesting to compare.

**Comment by Firas95k** [comment]
[Chameleon Macros.txt](https://github.com/user-attachments/files/17747518/Chameleon.Macros.txt)

Here it is

**Comment by u3dreal** [comment]
Thanks alot. I am implementing it in Happay Hare right now. If you want to test
[https://github.com/u3dreal/Happy-Hare/tree/v3beta](url)

**Comment by Firas95k** [comment]
> Thanks alot. I am implementing it in Happay Hare right now. If you want to test
> [https://github.com/u3dreal/Happy-Hare/tree/v3beta](url)

Your efforts are tremendous! Thank you✨ I would be happy to try it, is there a specific Readme or instructions for 3d Chameleon?
