### ISSUE TITLE
[Feature Request] Backup Files

### ISSUE THREAD

**Issue by FOLeader** [moggieuk/Happy-Hare#44]
Could you please create backup files of the config-files for HH2 like it is done with printer.cfg and others

**Comment by moggieuk** [comment]
It is!  the .../config/mmu directory is backed up. Look for directories like `mmu-20230902_114402`

**Comment by FOLeader** [comment]
Thank you for your feedback.
I thought more like it is done with the other cfg's.
In the same folder only named with date and bck, so you don't need to open ssh terminal

**Comment by moggieuk** [comment]
The problem is that there are many config files so it I think it is simpler to just backup the directory using the established klipper backup naming suffix.
