### ISSUE TITLE
eject tool on cancel issue

### ISSUE THREAD

**Issue by Darkchild971** [moggieuk/Happy-Hare#443]
This function does not seem to work whether the variable is "False" or "True" the filament is not ejected after a cancel

[gcode_macro _MMU_CLIENT_VARS]
description: Happy Hare client macro configuration variables
gcode: # Leave empty

variable_reset_ttg_on_cancel    : False		; True/False, Whether reset TTG map if print is canceled
variable_eject_tool_on_cancel   : True		; True/False, Whether to eject the tool on cancel
# You can extend functionality by adding a command (or call to your gcode macro)
variable_user_pause_extension   : ''		; Executed after the klipper base pause
variable_user_resume_extension  : ''		; Executed before the klipper base resume
variable_user_cancel_extension  : ''		; Executed before the klipper base cancel_print

**Comment by moggieuk** [comment]
Are you using my "client_macros.cfg" ?

**Comment by Darkchild971** [comment]
Thanks for your feedback. I use your macros and I disabled mine to avoid conflicts. The problem is apparently not there. The filament is correctly ejected at the end of printing

**Comment by moggieuk** [comment]
Great!
