### ISSUE TITLE
mmu_addon EREC cutter default servo duration is too short

### ISSUE THREAD

**Issue by ntchris** [moggieuk/Happy-Hare#454]
mmu_addon EREC cutter default config servo duration is too short

Recently I noticed the EREC servo cutter's angel is acting weird, the actual moved angel is always smaller than the requested angle , too little, not large enough as configed in the config file.

Did some investigation, finally realized it's the servo duration time is way to short.
It may have worked in some earlier version however in recent design changes in happy hare software and cutter beta7, a lot 
of things changed, for example, gear ratio is now 4:1, the servo may need to move full 180 degree,  therefore the time is too short.

it seems EREC cutter git repo dropped their config in their repo, so this repo is the only place to correct this.

_file config_klipper\config\mmu\addons\mmu_erec_cutter.cfg_
These variables control the servo movement
variable_servo_closed_angle   : 6	; Servo angle for closed postion with bowden aligned MMU
variable_servo_open_angle     : 170;  Servo angle to open up the cutter and move bowden away from MMU
**variable_servo_duration       : 0.4	; Time (s) of PWM pulse to activate servo  <===== this is way to short for cutter servo to move from about 10 to 170Degree ( or 0d to 180d  max).**

variable_servo_duration:  0.4 is too too short , suggest to change it to about 1.6s to 2 Seconds. 
angles should be easy for users to try and adjust , but this pwm time is a bit too tricky.
Thanks!

**Comment by moggieuk** [comment]
I'll update the servo_duration and (delay) in the v272 release.   I think it is because digital servos will latch on to a very short PWM burst and analog ones won't.  I have left the servo angles alone at the moment -- some servos are backward.  If the standard BOM build for EREC has servo with the angles you suggest I can update those too.  Would just like confirmation first.
