### ISSUE TITLE
Request: Add some kind of console message for belay sensor

### ISSUE THREAD

**Issue by checkitog** [moggieuk/Happy-Hare#455]
I recently installed a double belay sensor to relieve tension and compression, but it would be nice if the console would display something when one of the two positions has been pressed, I really don't know if it's working well in my case, beyond being able to make a MMU_SENSORS and see its status, I can't get more information.

**Comment by moggieuk** [comment]
This is available at the DEBUG level (log level 2).  So by default will go to the `mmu.log`.  You can choose what level in on the console vs log file.

I try to keep the console information to a minimum but I'm constantly tweaking to get the right level between INFO and DEBUG so may change this over time.
