### ISSUE TITLE
Happy Hare Install on Nebula pad Ender 3 v3 KE? is it possible?

### ISSUE THREAD

**Issue by SPYKE357** [moggieuk/Happy-Hare#457]
Good morning all

Hope you are all well.
I sent comms to k1-801, one of the K1 contributors asking the same question and he advised i should post here to see if anyone has had any success and if so, how?
sorry to bug you all with this issue of mine but i was wondering if it's possible to install HappyHare for a ERCF v2 kit i bought ( still to build) on the ender3v3ke/nebula pad? i'd like to keep the nebula pad if possible as the only other mcu i have is a pi zero 2(also not sure if there is a full klipper release for that printer...
the ke/nebula pad has been rooted and i see the boards are similar/same as the k1. been trying the last couple of days to install it but no luck so far... do you know if it's possible? and if so how and are there any limitations?

if i do this command through ssh "uname -m" it returns "mips" as a response.

Any and all help will be massively appreciated.

**Comment by SPYKE357** [comment]
-sh: ./install.sh: not found

this is returned when i run the ./install.sh line

**Comment by jacksky6** [comment]
@SPYKE357  
You can take a look at the record of my installation process on ender3v3 plus for reference.
I put it on youtube.

Here is the link:
https://www.youtube.com/watch?v=B0I6bcV8F6Y

**Comment by moggieuk** [comment]
Sorry, I have no way to help with this. But the "./install.sh not found" suggests you are not running from the Happy-Hare directory.  Did you:
```yml
cd ~/Happy-Hare
./install.sh
```?

**Comment by matthew73210** [comment]
> ender3v3



> [@SPYKE357](https://github.com/SPYKE357) You can take a look at the record of my installation process on ender3v3 plus for reference. I put it on youtube.
> 
> Here is the link: https://www.youtube.com/watch?v=B0I6bcV8F6Y

hey @jacksky6 , fyi the vid doesn't exist anymore
