### ISSUE TITLE
MMU issue: _MMU_STEP_HOME_EXTRUDER: Failed to reach extruder after moving 70.0mm

### ISSUE THREAD

**Issue by MDegelmann** [moggieuk/Happy-Hare#473]
Since the last update, the extruder sensor is no longer taken into account. It is displayed but unfortunately the loading no longer works and I keep getting this error :(

**Comment by moggieuk** [comment]
No `mmu.log` attached so I can't help without it.  The extruder sensor is still used -- that logic is unchanged.

**Comment by MDegelmann** [comment]
Fehler wurde durch das letzte Update verursacht. 
System komplett neu aufgespielt Problem gelöst
