### ISSUE TITLE
TMC extruder reports error: GSTAT after updating?

### ISSUE THREAD

**Issue by afllak** [moggieuk/Happy-Hare#480]
after instaling the last update v2.7.2-31-gab85033a this error messege start showing and the printer is shutdown and it happens when I'm loading the fillament into T0.

error message:
TMC 'extruder' reports error: GSTAT:      00000001 reset=1(Reset)
Once the underlying issue is corrected, use the
"FIRMWARE_RESTART" command to reset the firmware, reload the
config, and restart the host software.
Printer is shutdown.

Thank you.

**Comment by moggieuk** [comment]
This is unrelated to Happy Hare.  Klipper has some useful doc on the causes of this.

**Comment by afllak** [comment]
Ok, Thank you.
