### ISSUE TITLE
Where is the carrot?

### ISSUE THREAD

**Issue by EdwinPock** [moggieuk/Happy-Hare#499]
After the last update, the carrot icon disappeared on the display, as I press it, (When I press the empty place after carrots. :-) I enter the main panel but the carrot disappeared. 
How to recover it?

**Comment by ningpj** [comment]
Rerun the installer as a few icon's have changed to make HH more generic and less ERCF specific....The icon is now a pink happy hare :-)
```
cd ~/KlipperScreen/happy_hare
./install_ks.sh -g {num gates}
```

**Comment by moggieuk** [comment]
Yeah, as much as I like the carrot (and has a place in my heart) I will be releasing Happy Hare v3.0 soon which will extend support to many other MMU designs.

**Comment by EdwinPock** [comment]
Thanks it worked :

The Matrix: "Follow the Pink Rabbit" :-)

**Comment by cin3m** [comment]
Just an idea that came up my mind (I don't know how complicated the implementation could be): Can you enable the user to choose the desired icon as an optional step within the wizard?

Kind Regards

**Comment by Whitsend1000** [comment]
iS THIS THE PROPER CODE FOR 8 GATES: 
cd ~/KlipperScreen/happy_hare
./install_ks.sh -g {8}
