### ISSUE TITLE
K1 max with 4 individual steppers. No Selector. (AKA MMU type B)

### ISSUE THREAD

**Issue by tkunchick** [moggieuk/Happy-Hare#508]
I don't have a problem per se. Just looking to test MMU type B with my k1 max. I am using a BTT MMB to control the 4 individual steppers and pregate, post combiner filament sensors. probably replacing the default k1 filament sensor with a BTT smart sensor.

if there is a better way to offer testing, I couldn't find it.

**Comment by moggieuk** [comment]
Hi!  Well, with the launch of HH v3.0 (beta) you should be able to set this up.  An encoder is entirely optional but if you do use one it needs to have sufficient resolution (I feel about 1mm is perfect). I think the BTT smart sensor is about 8mm but I could be wrong.

I suggest you join the dedicated Happy Hare forum here: https://discord.gg/aABQUjkZPk

Then have a discussion in the "Other" area.
