### ISSUE TITLE
Home axis when ejecting tool

### ISSUE THREAD

**Issue by utzy79** [moggieuk/Happy-Hare#513]
Hi .
Not sure if this is a bug or intentional, but I can not eject the filament manually without homing the x,y znd z axis first.
Just seems odd as these 2 should not be relevant to each other.

5:28 PM
MMU issue: Error running _MMU_PRE_UNLOAD: Must home axis first: 180.000 180.000 2.250 [0.000].
Occured when unloading tool
5:28 PM
Must home axis first: 180.000 180.000 2.250 [0.000]
5:28 PM
Must home axis first: 180.000 180.000 2.250 [0.000]
5:28 PM
Must home axis first: 180.000 180.000 2.250 [0.000]

**Comment by moggieuk** [comment]
That wasn't intended - should just be a warning.  I'll take a look..
