### ISSUE TITLE
the icons disappeared in happy hare

### ISSUE THREAD

**Issue by EduardoFuchs** [moggieuk/Happy-Hare#525]
the happy hare icons are gone and the command to reinstall klipperscrem doesn't work cd ~/KlipperScreen/happy_hare
./install_ks.sh -g {8}
![putty_8uKFQAF40w](https://github.com/user-attachments/assets/a5e4d105-a1c8-4aa0-b40e-4377f00d589a)
![IMG_20241118_211420](https://github.com/user-attachments/assets/c822b9e6-8420-456c-b2cd-4a4d68373a2a)

**Comment by ningpj** [comment]
The install command is ``./install_ks.sh -g 8`` not ``./install_ks.sh -g {8}``
