### ISSUE TITLE
V3 MMU_CALIBRATE_SECTOR BYPASS=1 Crash

### ISSUE THREAD

**Issue by BreeOge** [moggieuk/Happy-Hare#535]
I ran across an issue today on V3 latest as of right now.  I am re-calibrating my gates, and everything works, however when I get to MMU_CALIBRATE_SECTOR BYPASS=1 it crashes.  All the other gates worked just fine.  I rebooted multiple times to try and resolve the issue, but to no avail.

8:05 PM
MMU_CALIBRATE_SELECTOR BYPASS=1
8:05 PM
DEBUG: Setting servo to move (filament hold) position at angle: 109
8:05 PM
Measuring the selector position for bypass...
8:05 PM
Selector move measured 179.1mm
8:05 PM
Klipper state: Shutdown
8:05 PM
Internal error on command:"MMU_CALIBRATE_SELECTOR"

**Comment by moggieuk** [comment]
Thanks. This is now fixed in the v3beta update I just pushed.    The restructuring of the code for the v3 release introduced a few regressions...
