### ISSUE TITLE
Inconsistent variable names between client_macros.cfg and mmu_macro_vars.cfg

### ISSUE THREAD

**Issue by iamnotahippy** [moggieuk/Happy-Hare#540]
Specifically, the variable to unload filament on a cancel condition is ```variable_unload_tool_on_cancel``` in mmu_macro_vars.cfg and ```eject_tool_on_cancel``` in client_macros.cfg

**Comment by moggieuk** [comment]
Thanks.  Yes, this was a bug. Fixed in latest "v3beta" push.  Correct term should be "unload_tool_on_cancel" because there is now a subtle difference between "unload" and "eject" (which pushes filament beyond parking position).
