### ISSUE TITLE
MMU_EJECT or MMU_UNLOAD without sync_form_tip cause runout error

### ISSUE THREAD

**Issue by spikeygg** [moggieuk/Happy-Hare#556]
On HH v2.73 I dynamically used `MMU_EJECT` in my `PRINT_END` routine to unload the filament. After the upgrade to v3.01 I found that this unload operation was causing the runout to trigger. I tried changing the `MMU_EJECT` to a `MMU_UNLOAD` based on some comments in discord, it didn't seem to help.

Watching the print end when this happened I could see that the filament wasn't able to move in the encoder but it was performing the correct movements on the extruder. This was causing the Bowden tube to rock back and forth in the  chamber as the process happened. When I turned on `sync_form_tip` the runout problem went away, presumably because the encoder could read the amount the filament was moving during the tip forming process.

Here's a klippy.log capturing the issue: [klippy.log](https://github.com/user-attachments/files/18134212/klippy.log)

**Comment by moggieuk** [comment]
Just fixed.  You probably should be using `MMU_UNLOAD` instead of `MMU_EJECT` but the runout suppression has been corrected for MMU_EJECT as well.

Read the release notes of the subtle difference now between MMU_UNLOAD and MMU_EJECT.
