### ISSUE TITLE
Gear stepper run current restored to 100% before collision homing is detected.

### ISSUE THREAD

**Issue by slobba** [moggieuk/Happy-Hare#56]
I've just re-installed Happy-Hare after upgrading my ERCF with the Binky encoder. I have selected collision detection for the gear stepper and have set the gear stepper current to 10% for collision detection in the mmu_parameters.cfg file. However, it appears that the gear stepper current is restored back to 100% before collision detection has occurred. This is a snippet of the mmu.log:

20:34:00 - - TRACE: Course loading move #1 into bowden. Stepper: 'gear' moved 835.5mm, encoder measured 830.0mm (delta 5.5mm)
20:34:00 MMU [T4] >>> [En] >>>>>>> [Ex] ... [Nz] (@876.5 mm)
20:34:00 - DEBUG: Homing to extruder gear, up to 50.0mm in 3.0mm steps
20:34:00 Modifying gear_stepper run current to 10% for collision detection
20:34:01 Restoring gear_stepper run current to 100% configured
20:34:01 - - TRACE: Homing step #1. Stepper: 'gear' moved 3.0mm, encoder measured 2.9mm (delta 0.1mm)
20:34:02 - - TRACE: Homing step #2. Stepper: 'gear' moved 3.0mm, encoder measured 2.9mm (delta 0.1mm)
20:34:02 - - TRACE: Homing step #3. Stepper: 'gear' moved 3.0mm, encoder measured 1.9mm (delta 1.1mm)
20:34:03 - - TRACE: Homing step #4. Stepper: 'gear' moved 3.0mm, encoder measured 2.9mm (delta 0.1mm)
20:34:03 - - TRACE: Homing step #5. Stepper: 'gear' moved 3.0mm, encoder measured 1.9mm (delta 1.1mm)
20:34:04 - - TRACE: Homing step #6. Stepper: 'gear' moved 3.0mm, encoder measured 2.9mm (delta 0.1mm)
20:34:05 - - TRACE: Homing step #7. Stepper: 'gear' moved 3.0mm, encoder measured 0.0mm (delta 3.0mm)
20:34:05 - DEBUG: Extruder entrance found after 21.0mm move (7 steps), encoder measured 15.5mm (total_delta 5.5mm)

**Comment by moggieuk** [comment]
Oops. That isn't good. Let me check...  What is the version of Happy Hare you are using (as reported by moonraker)?
