### ISSUE TITLE
Configuration Hardware.cfg for tmc2240 driver

### ISSUE THREAD

**Issue by daTobi1** [moggieuk/Happy-Hare#59]
Hello,

i have an ebb sb2240 toolboard on my extruder with spi. I configurate the hardware.cfg by this:

[tmc2240 manual_extruder_stepper extruder]
cs_pin: EBBCan: PA15
spi_software_sclk_pin: EBBCan: PB10
spi_software_mosi_pin: EBBCan: PB11
spi_software_miso_pin: EBBCan: PB2
driver_TPFD: 0
run_current: 0.650
stealthchop_threshold: 999999

and get this error by klipper:

No section: 'manual_extruder_stepper extruder'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

what is wrong

**Comment by moggieuk** [comment]
Sorry for the delay.  Is this still a problem for you?  The tmc2240 should be supported.   I'd need the `mmu_hardware.cfg`, your `[extruder]` definition in printer.cfg and ideally a `klippy.log` to diagnose.

BTW I'm going to be pushing a new release this week that will REMOVE the need to customize the configuration of the extruder ..!  That will certainly solve your problem.
