### ISSUE TITLE
install.sh overwrites form_tip_macro: _MMU_CUT_TIP in parameters.cfg

### ISSUE THREAD

**Issue by AMFkuna** [moggieuk/Happy-Hare#61]
install.sh overwrites form_tip_macro: _MMU_CUT_TIP in parameters.cfg
and custom code on MMU_CUT_TIP in software.cfg

**Comment by moggieuk** [comment]
Yes it does although it copies the old files as backup.  This is not something that is easy to automate and not something I'm planning.  The best option is to set `form_tip_macro: <your_macro_name>`. and store that macro outside of `mmu_software.cfg`.  The form_tip_macro setting will be retained on updates /upgrades.
