### ISSUE TITLE
Better instructions required for extruder settings when extruder driver is NOT connected through UART

### ISSUE THREAD

**Issue by k1-801** [moggieuk/Happy-Hare#68]
I am currently trying to setup a ERCF unit on my FlyingBear Ghost 5. ERCF seems to be well-fitted for Vorons, but not for off the shelf printers, such as this one.
The Happy Hare configuration strictly mandates to move the extruder configuration to the mmu_hardware file, including the tmmc2209 section, which is used for UART connected drivers. What if the extruder is not connected through UART and does not have any means of feedback? Is it still possible to configure the Happy Hare for such a machine? If so, how should I arrange that?

**Comment by moggieuk** [comment]
It is possible but I have an upcoming release that will be posted very soon that no longer requires any change to the Extruder stepper definition -- will 100% solve your concerns.
