### ISSUE TITLE
Toolhead Board (Ebb36) Diag pin Sensorless  "touch" homing?

### ISSUE THREAD

**Issue by mochoandre** [moggieuk/Happy-Hare#77]
Is it possible to use extruder  diag pin in EBB36 so i can use the "touch" fuction in homing to nozzle in new HAPPY-HARE V2?

**Comment by mrmultifunk** [comment]
I don't think the ebb36 has the diag pin connected. I can look it up in the schematic when i'm back on the pc.

**Comment by mochoandre** [comment]
I Also think that but just checking if someone and a better in depth information or a workaround

**Comment by Surion79** [comment]
The diagrams on EBB36 and EBB42 do not show a DIAG pin defined, only ENABLE, DIR, STEP, UART. 
EBB SB2240 and SB2209 have DIAG pins.

**Comment by mochoandre** [comment]
Thank you. I have a EBB SB2240 but can not use it with my lgx lite

**Comment by moggieuk** [comment]
This doesn't sound like an issue. Can I close this out?

BTW the "home to nozzle" functionality is pretty cool but definitely experimental and needs careful tuning of stall guard to get the just right.
