### ISSUE TITLE
Moonraker Notifier support not triggering on pauses due to clogs or swap fails

### ISSUE THREAD

**Issue by Cyberwizzard** [moggieuk/Happy-Hare#83]
Moonraker has a Notifier component which allows state changes to be sent through PushOver or other services: https://moonraker.readthedocs.io/en/latest/configuration/#notifying-from-klipper

My setup notifies me on print starts, stops and emergency stops, but not on pauses triggered by HappyHare v2.

Are the events named differently when HH triggers a pause? Or does it not trigger the pause event in Moonraker at all? Can we get support for this framework, or if its already supported, document how its supposed to be set up?

**Comment by moggieuk** [comment]
I'm not sure, I haven't seen this framework before.  A Happy Hare "pause" still runs Klipper pause so I'm not sure why it would look any different to PushOver.   I'll mark this as an enhancement and take a deeper look when I can

**Comment by moggieuk** [comment]
I marked as "won't fix" because I don't think there is anything else I can do.  The default PAUSE macro is called by Happy Hare.  Also, the macro called can be overridden.  I don't know why moonraker isn't seeing the state change, but the print is definitely paused.

**Comment by pnewb** [comment]
@Cyberwizzard is it possible that you’re just missing the paused event? Hard to know without seeing your config, but mine works fine with pauses and looks like this: 

```
[notifier pushover]
url: pover://myspecialurlgoeshere
events: complete, error, paused
title: printer notification
body: "The status of Trident has changed to {event_name}"
```
