### ISSUE TITLE
Option 'microsteps' in section 'extruder' must be specified

### ISSUE THREAD

**Issue by kerkmann** [moggieuk/Happy-Hare#86]
Since the newest version `v2.2.0` I am getting the error message `Option 'microsteps' in section 'extruder' must be specified
`. The strange part is, the printer is working without Happy Hare. But when I install it (doesn't matter if I migrate or do a clean install), I am getting the error message `Option 'microsteps' in section 'extruder' must be specified
`. :(

What information do you need and has someone the same issue?

printer.cfg
```cfg
[extruder]
step_pin: EBBCan: PD0
dir_pin: !EBBCan: PD1
enable_pin: !EBBCan: PD2
rotation_distance: 22.125180456897
gear_ratio: 50:10
microsteps: 16
full_steps_per_rotation: 200
nozzle_diameter: 0.400
filament_diameter: 1.75
heater_pin: EBBCan: PB13
sensor_type: Generic 3950
sensor_pin: EBBCan: PA3
min_temp: 10
max_temp: 270
max_power: 1.0
min_extrude_temp: 170
control: pid
pid_kp: 26.213
pid_ki: 1.304
pid_kd: 131.721
pressure_advance: 0.05
pressure_advance_smooth_time: 0.040
max_extrude_only_distance: 200
max_extrude_cross_section: 50.0

[tmc2240 extruder]
cs_pin: EBBCan: PA15
spi_software_sclk_pin: EBBCan: PB10
spi_software_mosi_pin: EBBCan: PB11
spi_software_miso_pin: EBBCan: PB2
driver_TPFD: 0
run_current: 0.650
stealthchop_threshold: 0
```

[klippy.log](https://github.com/moggieuk/Happy-Hare/files/13342968/klippy.2.log)

**Comment by shaneshort** [comment]
I'm having the exact same issue after upgrading this morning.

**Comment by shaneshort** [comment]
@kerkmann after spending a lot of time digging around in code I don't quite understand, it looks like the immediate fix for me, is to include the mmu configuration *after* the extruder is defined in the config. I originally had it at top.

 @moggieuk from what I can understand a 'extras.mmu_toolhead.MmuExtruderStepper' object is instantiated by HappyHare which inherits from the extruder. I can see there's a callback function registered to insert this object once klippy connects, but It seems if this is instantiated before the extruder is, it errors.

**Comment by moggieuk** [comment]
Yes. this logic is tricky and there was a reason for the order of things but clearly it is generating problems for folks.  The workaround (until I get back home to my printer .. in about 3 days) is to move the `[include mmu/base/*.cfg]` to AFTER the extruder definition in the printer.cfg file.

**Comment by kerkmann** [comment]
@moggieuk thank you very much for your quick response. Can we add it to the README or the install script somewhere? Otherwise it's a little bit misleading. :)

Thank! :heart:

**Comment by kerkmann** [comment]
Can confirm, moving them under the `extruder` definition is solving the problem. It was a good step to force me to split my `printer.cfg`. Now it's much cleaner. :P

```cfg
[include printer/base.cfg]
[include printer/mcu.cfg]

[include printer/bed_mesh.cfg]
[include printer/display.cfg]
[include printer/extruder.cfg]
[include printer/fan.cfg]
[include printer/heater_bed.cfg]
[include printer/homing.cfg]
[include printer/input_shaper.cfg]
[include printer/led.cfg]
[include printer/probe.cfg]
[include printer/stepper_x.cfg]
[include printer/stepper_y.cfg]
[include printer/stepper_z.cfg]
[include printer/temperature_sensor.cfg]

[include mmu/base/*.cfg]
[include mmu/optional/client_macros.cfg]
[include mmu/optional/mmu_menu.cfg]

[include macros.cfg]
[include mainsail.cfg]
[include nevermore.cfg]
[include timelapse.cfg]
```
