### ISSUE TITLE
Installation on multiple instances fails on checking the service name

### ISSUE THREAD

**Issue by cicinovec** [moggieuk/Happy-Hare#90]
install.sh script, line 95
Script is searching for a service called klipper.service
But on installations with multiple instances the service name is different, mostly klipper-[name].service

When changing the line, the installation proceeds with no other issues
See in attached file my file as example
[install.zip](https://github.com/moggieuk/Happy-Hare/files/13403008/install.zip)

**Comment by NNGB-kor** [comment]
Installation also failed in multi-instance.
It tells me to install klipper first.

**Comment by cicinovec** [comment]
Hi @moggieuk, with multiple instances you got `printer_data` renamed to `{whatevername}_data` (you can use `-c` and `-k`) but also the service name is changes to this format `klipper-{whatevername}.service`
The script should use `whatevername` as variable and use this variable to check klipper service availability.
This is as far as I can get with my programming knowledge. I can test it for you, but dont know how to update the script properly (in my installation I have changed the line directly to my service name `klipper-Voron24.service`)
![2023-12-10 21_11_09-pi@IDEXKlipper_ ~](https://github.com/moggieuk/Happy-Hare/assets/33634908/d3abe7da-9d0e-40da-8717-e7f81de362b8)

**Comment by yourbuddydinec** [comment]
I edited the current script to include a -n style command for printer name and it seems to install okay but get this error at the end. Is this "normal" or so I need to change things? 
Was able to install with `./install.sh -i -n E3 -z` with E3 being the name of my printer
![image](https://github.com/moggieuk/Happy-Hare/assets/52755257/04791135-a688-4f0e-9489-bbf22bd6f510)
