### ISSUE TITLE
updated to version: v2.2.0-5-gaa231409 --> Option 'step_pin' is not valid in section 'stepper_mmu_gear'

### ISSUE THREAD

**Issue by Eisbaeeer** [moggieuk/Happy-Hare#93]
I reinstalled happy-hare from the srcatch after failure with the update by moving all [extruder] settings from hh to printer.cfg
Ít worked like a charme. Today next update and now get the following error:

`Option 'step_pin' is not valid in section 'stepper_mmu_gear'`

**Comment by ningpj** [comment]
This unfortunately is a known issue....while its investigated, you can work around this by either moving your [include mmu/base/*.cfg] until after your [extruder] section or export your [extruder] section to a separate file and include it before these.

**Comment by noolsr** [comment]
Hey moved my [extruder] section out of my printer config, included it before my [include mmu/base/*.cfg]. Still shows the same error. Any new updates on the bug?

**Comment by moggieuk** [comment]
This shouldn't be a problem... sometimes I've seen it with incorrect pin_alias.  There used to be an issue with `[include]` order but as far as I'm aware that was fixed about a month ago with v2.2 update.

If, after upgrading to latest, you still have issues. Attach your `klippy.log`

Going to mark and not_a_bug / need_info

**Comment by Riconec** [comment]
have the same error, first time installing HH

**Comment by hfog** [comment]
Just upgraded Klipper (to deal with a different issue) and also HH and now I'm hitting this same error.
None of the suggestions elsewhere in this thread made any difference.

**Comment by Riconec** [comment]
I installed HH and got a lot of issues, googling issues came up here someone told to update klipper so I did and the problems were still there. After of hour of strugles I decided to just start over and reinstall HH (after I updated klipper) and this time it worked without step_pin issue

**Comment by noolsr** [comment]
Can confirm this works did the same and the error is gone.

**Comment by iBral** [comment]
i have same error, when i update klipper
