### ISSUE TITLE
Clog detection after reset detection length

### ISSUE THREAD

**Issue by Eisbaeeer** [moggieuk/Happy-Hare#97]
Setup: automatic clog detection enabled.
Issue: I get a clog detection always after reset detection length. The sensor is working 100% properly.

Log: 

08:32:33 - DEBUG: Enabled encoder sensor, force_in_print=True. Status: {'encoder_pos': 0.7, 'detection_length': 11.9, 'min_headroom': 11.9, 'headroom': 19.9, 'desired_headroom': 8.0, 'detection_mode': 2, 'enabled': False, 'flow_rate': 0}
09:17:38 - DEBUG: Automatic clog detection: new min_headroom (< 8.0mm desired): 7.9mm
09:17:38 - DEBUG: Automatic clog detection: new min_headroom (< 8.0mm desired): 7.2mm
09:17:38 - DEBUG: Automatic clog detection: new min_headroom (< 8.0mm desired): 6.5mm
09:17:39 - DEBUG: Automatic clog detection: new min_headroom (< 8.0mm desired): 5.3mm
09:17:39 - DEBUG: Automatic clog detection: new min_headroom (< 8.0mm desired): 4.1mm
09:17:39 - DEBUG: Automatic clog detection: new min_headroom (< 8.0mm desired): 3.0mm
09:17:39 - DEBUG: Automatic clog detection: new min_headroom (< 8.0mm desired): 2.2mm
09:17:40 - DEBUG: Automatic clog detection: new min_headroom (< 8.0mm desired): 1.6mm
09:17:40 - DEBUG: Automatic clog detection: new min_headroom (< 8.0mm desired): 0.4mm
09:17:40 - DEBUG: Automatic clog detection: new min_headroom (< 8.0mm desired): -0.6mm
09:17:40 Issue on tool T4
09:17:40 - DEBUG: Automatic clog detection: new min_headroom (< 8.0mm desired): -1.5mm
09:17:41 - DEBUG: Automatic clog detection: new min_headroom (< 8.0mm desired): -2.2mm
09:17:41 - DEBUG: Automatic clog detection: new min_headroom (< 8.0mm desired): -3.5mm
09:17:41 - DEBUG: Automatic clog detection: new min_headroom (< 8.0mm desired): -4.7mm
09:17:42 - DEBUG: Saving toolhead position for runout
09:17:42 - DEBUG: Checking if this is a clog or a runout (state 8)...
09:17:42 - DEBUG: Checking for filament at gate...
09:17:42 - DEBUG: Setting servo to down (filament drive) position at angle: 140
09:17:44 - - TRACE: After buzzing gear motor, encoder measured 4.45
09:17:44 - DEBUG: Filament detected in encoder after buzzing gear motor
09:17:44 - DEBUG: Automatic clog detection: maintaining headroom by adding 8.0mm to detection_length
09:17:44 - DEBUG: Automatic clog detection: reset detection_length to 19.9mm
09:17:44 An issue with the MMU has been detected. Print paused
         Reason: A clog has been detected and requires manual intervention
09:17:44 After fixing the issue, call 'RESUME' to continue printing (MMU_UNLOCK can restore temperature)
09:17:44 - - TRACE: Extruder heater will be disabled in 10 minutes 0 seconds
09:17:44 - DEBUG: Disabled encoder sensor. Status: {'encoder_pos': 6111.5, 'detection_length': 19.9, 'min_headroom': 19.9, 'headroom': 27.9, 'desired_headroom': 8.0, 'detection_mode': 2, 'enabled': True, 'flow_rate': 0}
09:17:44 - DEBUG: Asked to save toolhead position for pause but it is already saved for runout. Ignored
09:17:44 - DEBUG: Lifting toolhead 5.0mm
09:17:44 - DEBUG: Job State: PRINTING -> PAUSE_LOCKED (MMU State: Encoder: Disabled, Synced: False, Paused temp: 245.0, Resume to state: printing, Position saved: runout, z_hop @5.0mm, pause_resume: False, Idle timeout: 72000.00s)
09:17:44 - - TRACE: Running macro: _MMU_PRINT_STATE_CHANGED STATE='pause_locked' OLD_STATE='printing'
09:17:44 - DEBUG: Setting servo to up (filament released) position at angle: 30
09:17:44 - - TRACE: Running macro: PAUSE
09:17:44 - - TRACE: MMU PAUSE wrapper called
09:17:44 - - TRACE: Running macro: __PAUSE
09:17:50 - - TRACE: Processing idle_timeout 'ready' event

**Comment by moggieuk** [comment]
Almost certainly because you are moving extruder too fast (a purge line perhaps or pushing too fast to the purge tower?)

This issue has come up a number of times and reducing extruder speed (often in slicer settings) to avoid skipped steps fixes it.
